/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.9
 * Generated at: 2019-07-24 04:37:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class a_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery-1.7.2.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction register()\r\n");
      out.write("\t{\r\n");
      out.write("\t \tvar $mobile=$(\"#mobile\").val();\r\n");
      out.write("\t /* \t\t$.ajax({\r\n");
      out.write("\turl:\"MobileServlet\",\r\n");
      out.write("\t请求方式:\"post\",\r\n");
      out.write("\tdata:\"mobile=\"+$mobile,\r\n");
      out.write("\tsuccess:function(result,testStatus)\r\n");
      out.write("\t{\r\n");
      out.write("\tif(result==\"true\")\r\n");
      out.write("\t\t{alert(\"号码已存在，请更换\");\r\n");
      out.write("\t\t}else\r\n");
      out.write("\t\t{alert(\"注册成功！\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t},\r\n");
      out.write("\terror:function(xhr,errorMessage,e)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"系统异常\");\r\n");
      out.write("\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t$.post(\r\n");
      out.write("\t\"MobileServlet\",\r\n");
      out.write("\t\"mobile=\"+$mobile,\r\n");
      out.write("\tfunction(result){\r\n");
      out.write("\tif(result==\"true\")\r\n");
      out.write("\t\t{alert(\"号码已存在，请更换\");\r\n");
      out.write("\t\t}else\r\n");
      out.write("\t\t{alert(\"注册成功！\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t},\r\n");
      out.write("\t\"text\"\r\n");
      out.write("\t); \r\n");
      out.write("\t$(\"#tip\").load(\r\n");
      out.write("\t\t\"MobileServlet\",\r\n");
      out.write("\t\t\"mobile=\"+$mobile\r\n");
      out.write("\t\t);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//JSON\r\n");
      out.write("\t\tvar student={\"name\":\"zs\",\"age\":23};\r\n");
      out.write("\t\t//alert(student.name+\"--\"+student.age);\r\n");
      out.write("\t\t//var name=[\"xxx\",\"xx\",\"xx\"]\r\n");
      out.write("\t\tvar students=[\r\n");
      out.write("\t\t\t\t{\"name\":\"zs\" , \"age\":23},\r\n");
      out.write("\t\t\t\t{\"name\":\"ls\",\"age\":24},\r\n");
      out.write("\t\t\t\t{\"name\":\"ww\",\"age\":25}\r\n");
      out.write("\t\t];\r\n");
      out.write("\t\talert(students[1].name+\"--\"+students[1].age);\r\n");
      out.write("\t\t*/\r\n");
      out.write("\t\t$.getJSON(\r\n");
      out.write("\t\t\t\"MobileServlet\",\r\n");
      out.write("\t\t//\t\"mobile=\"+$mobile,\r\n");
      out.write("\t\t\t{\"mobile\":$mobile},//\"a\":\"b\",\"c\":\"d\",json的优势在于传参可以快速地写多个\r\n");
      out.write("\t\t\tfunction(result){//msg:true|false\r\n");
      out.write("\t\t\t\t\tif(result.msg==\"true\")\r\n");
      out.write("\t\t\t\t\t{alert(\"号码已存在，请更换\");\r\n");
      out.write("\t\t\t\t\t}else\r\n");
      out.write("\t\t\t\t\t{alert(\"注册成功！\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction testJson()\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t$.getJSON(\r\n");
      out.write("\t\t\t\"JsonServlet\",\r\n");
      out.write("\t\t\t{\"name\":\"zs\",\"age\":24},\r\n");
      out.write("\t\t\tfunction(result){\r\n");
      out.write("\t\t\t\t\t//js需要通过eval()函数，将返回值转为一个js能够识别的json对象\r\n");
      out.write("\t\t\t\t\tvar json=eval(result);//var jsonStudent=eval(result.stu1);\r\n");
      out.write("\t\t\t\t\t$.each(json,function(i,element){//i表示下标，element表示当前元素\r\n");
      out.write("\t\t\t\t\talert(this.name+\"---\"+this.age);\r\n");
      out.write("\t\t\t\t\t})//alert(jsonStudent.name+\"--\"+jsonStudent.age);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t);\r\n");
      out.write("\t\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script>\"undefined\"==typeof CODE_LIVE&&(!function(e){var t={nonSecure:\"63900\",secure:\"63905\"},c={nonSecure:\"http://\",secure:\"https://\"},r={nonSecure:\"127.0.0.1\",secure:\"gapdebug.local.genuitec.com\"},n=\"https:\"===window.location.protocol?\"secure\":\"nonSecure\";script=e.createElement(\"script\"),script.type=\"text/javascript\",script.async=!0,script.src=c[n]+r[n]+\":\"+t[n]+\"/codelive-assets/bundle.js\",e.getElementsByTagName(\"head\")[0].appendChild(script)}(document),CODE_LIVE=!0);</script></head>\r\n");
      out.write("<body data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-0\" data-genuitec-path=\"/ajax01/WebRoot/a.jsp\">\r\n");
      out.write("\t\t手机<input id=\"mobile\" data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-0\" data-genuitec-path=\"/ajax01/WebRoot/a.jsp\"/>\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t\t<input type=\"button\" value=\"注册\" onclick=\"register()\"/>\r\n");
      out.write("\t\t<span id=\"tip\"></span>\r\n");
      out.write("\t\t<input type=\"button\" value=\"测试json\" onclick=\"testJson()\"/>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
