/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.9
 * Generated at: 2020-01-12 12:28:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class HydropowerQueryMaintenance_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/c.tld", Long.valueOf(1578831990861L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("   <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
      out.write(" \t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "BaseJsp.jsp", out, false);
      out.write("\r\n");
      out.write("\t <script type=\"text/javascript\">\r\n");
      out.write("\t var datagrid;\r\n");
      out.write("\tvar searchForm;\r\n");
      out.write("\t $(function(){\r\n");
      out.write("\t searchForm=$('#form1').form();\r\n");
      out.write("\t datagrid=$('#datagrid').datagrid({\r\n");
      out.write("\t\turl:'allWaterElectric.action',\r\n");
      out.write("\t\ticonCls:'icon-save',\r\n");
      out.write("\t\tpagination:true,\r\n");
      out.write("\t\tpageSize:30,\r\n");
      out.write("\t\tpageList:[ 10,20,30,40],\r\n");
      out.write("\t\tfit:true,\r\n");
      out.write("\t\tfitColums:false,\r\n");
      out.write("\t\tnowarp:false,\r\n");
      out.write("\t\tborder:false,\r\n");
      out.write("\t\tidField:'id',\r\n");
      out.write("\t\tfrozenColumns : [ [\r\n");
      out.write("\t\t  {field:'controller',\r\n");
      out.write("            title:'修改',\r\n");
      out.write("            width:50,\r\n");
      out.write("            align : 'center',\r\n");
      out.write("                formatter : function (value,row,index)\r\n");
      out.write("\t             {\r\n");
      out.write("\t              return '<a href=\"SearchDepartmentAndUsergroup('+index+');\">修改</a>';\r\n");
      out.write("\t             }\r\n");
      out.write("            },\r\n");
      out.write("\t\t{\r\n");
      out.write("            field:'id',\r\n");
      out.write("            title:'序号',\r\n");
      out.write("            width:50,\r\n");
      out.write("            align : 'center'\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("            field:'Name',\r\n");
      out.write("            title:'姓名',\r\n");
      out.write("            width:50,\r\n");
      out.write("            align : 'center'\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("            field:'salaryNum',\r\n");
      out.write("            title:'工资号',\r\n");
      out.write("            width:50,\r\n");
      out.write("            align : 'center'\r\n");
      out.write("            }\r\n");
      out.write("            ]],\r\n");
      out.write("             columns:[[\r\n");
      out.write("           {\r\n");
      out.write("            field:'buildingName',\r\n");
      out.write("            title:'楼名',\r\n");
      out.write("            width:50,\r\n");
      out.write("            align : 'center'\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("            field:'uName',\r\n");
      out.write("            title:'单元',\r\n");
      out.write("            width:50,\r\n");
      out.write("            align : 'center'\r\n");
      out.write("            }, {\r\n");
      out.write("            field:'Season',\r\n");
      out.write("            title:'季度',\r\n");
      out.write("            width:50,\r\n");
      out.write("            align : 'center'\r\n");
      out.write("            }, {\r\n");
      out.write("            field:'lastelectricNum',\r\n");
      out.write("            title:'电上次表低',\r\n");
      out.write("            width:50,\r\n");
      out.write("            align : 'center'\r\n");
      out.write("            }, {\r\n");
      out.write("            field:'electricNum',\r\n");
      out.write("            title:'电本季读数',\r\n");
      out.write("            width:50,\r\n");
      out.write("            align : 'center'\r\n");
      out.write("            },{\r\n");
      out.write("            field:'Bill',\r\n");
      out.write("            title:'电本季度数',\r\n");
      out.write("            width:50,\r\n");
      out.write("            align : 'center',\r\n");
      out.write("            formatter: function(value,row,index){return row.electricNum-row.lastelectricNum;}\r\n");
      out.write("            },{\r\n");
      out.write("            field:'electricBill',\r\n");
      out.write("            title:'电单价',\r\n");
      out.write("            width:50,\r\n");
      out.write("            align : 'center'\r\n");
      out.write("            },{\r\n");
      out.write("            field:'electricmoney',\r\n");
      out.write("            title:'电金额',\r\n");
      out.write("            width:50,\r\n");
      out.write("            align : 'center',\r\n");
      out.write("            formatter: function(value,row,index){return (row.electricNum-row.lastelectricNum)*row.electricBill;}\r\n");
      out.write("            },{\r\n");
      out.write("            field:'lastewaterNum',\r\n");
      out.write("            title:'水上次表低',\r\n");
      out.write("            width:50,\r\n");
      out.write("            align : 'center'\r\n");
      out.write("            }, {\r\n");
      out.write("            field:'waterNum',\r\n");
      out.write("            title:'水本季读数',\r\n");
      out.write("            width:50,\r\n");
      out.write("            align : 'center'\r\n");
      out.write("            },{\r\n");
      out.write("            field:'Bill1',\r\n");
      out.write("            title:'水本季方数',\r\n");
      out.write("            width:50,\r\n");
      out.write("            align : 'center',\r\n");
      out.write("            formatter: function(value,row,index){return row.waterNum-row.lastewaterNum;}\r\n");
      out.write("            },{\r\n");
      out.write("            field:'waterBill',\r\n");
      out.write("            title:'水单价',\r\n");
      out.write("            width:50,\r\n");
      out.write("            align : 'center'\r\n");
      out.write("            },{\r\n");
      out.write("            field:'watermoney',\r\n");
      out.write("            title:'水金额',\r\n");
      out.write("            width:50,\r\n");
      out.write("            align : 'center',\r\n");
      out.write("            formatter: function(value,row,index){return (row.waterNum-row.lastewaterNum)*row.waterBill;}\r\n");
      out.write("            },{\r\n");
      out.write("            field:'addition',\r\n");
      out.write("            title:'备注',\r\n");
      out.write("            width:50,\r\n");
      out.write("            align : 'center'\r\n");
      out.write("            }\r\n");
      out.write("            ]],\r\n");
      out.write("            onLoadSuccess:function(data)\r\n");
      out.write("            {\r\n");
      out.write("            \t\r\n");
      out.write("\t            $('#year').combobox({\r\n");
      out.write("\t\t\t        url:'waterElectricYear.action',\r\n");
      out.write("\t\t\t        prompt:'年份',\r\n");
      out.write("\t\t\t        valueField : 'season',\r\n");
      out.write("\t\t\t        textField : 'season',\r\n");
      out.write("\t\t\t        groupField :'season'\r\n");
      out.write("\t\t\t    });\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t     $('#building').combobox({\r\n");
      out.write("\t\t\t        url:'waterElectricYear.action',\r\n");
      out.write("\t\t\t         prompt:'楼名',\r\n");
      out.write("\t\t\t        valueField : 'season',\r\n");
      out.write("\t\t\t        textField : 'season',\r\n");
      out.write("\t\t\t        groupField :'season'\r\n");
      out.write("\t\t\t    });\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t       $('#unit').combobox({\r\n");
      out.write("\t\t\t        url:'waterElectricYear.action',\r\n");
      out.write("\t\t\t         prompt:'单元',\r\n");
      out.write("\t\t\t        valueField : 'season',\r\n");
      out.write("\t\t\t        textField : 'season',\r\n");
      out.write("\t\t\t        groupField :'season'\r\n");
      out.write("\t\t\t    });\r\n");
      out.write("            }\r\n");
      out.write("\t \t});\r\n");
      out.write("\t \t    \r\n");
      out.write("\t \t    \tsearch_user=function ()\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t$('#datagrid').datagrid('load',{\r\n");
      out.write("\t\t\t\t\t\t\tyear:$('#year').val(),\r\n");
      out.write("\t\t\t\t\t\t\tseason:$('#season').val(),\r\n");
      out.write("\t\t\t\t\t\t\tname1:$('#name1').val(),\r\n");
      out.write("\t\t\t\t\t\t\tid1:$('#id1').val(),\r\n");
      out.write("\t\t\t\t\t\t\tsalaryNum:$('#salaryNum').val(),\r\n");
      out.write("\t\t\t\t\t\t\tbuilding:$('#building').val(),\r\n");
      out.write("\t\t\t\t\t\t\tunit:$('#unit').val(),\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t \t    \r\n");
      out.write("\t \t    clear_data=function()\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t$('#datagrid').datagrid('load',{});\r\n");
      out.write("\t\t\tsearchForm.find('input').val('');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t });\r\n");
      out.write("\t </script>\r\n");
      out.write("  <script>\"undefined\"==typeof CODE_LIVE&&(!function(e){var t={nonSecure:\"63900\",secure:\"63905\"},c={nonSecure:\"http://\",secure:\"https://\"},r={nonSecure:\"127.0.0.1\",secure:\"gapdebug.local.genuitec.com\"},n=\"https:\"===window.location.protocol?\"secure\":\"nonSecure\";script=e.createElement(\"script\"),script.type=\"text/javascript\",script.async=!0,script.src=c[n]+r[n]+\":\"+t[n]+\"/codelive-assets/bundle.js\",e.getElementsByTagName(\"head\")[0].appendChild(script)}(document),CODE_LIVE=!0);</script></head>\r\n");
      out.write("  \r\n");
      out.write("  <body data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-1\" data-genuitec-path=\"/Hydropower_query_system/WebRoot/HydropowerQueryMaintenance.jsp\">\r\n");
      out.write("\t   <div id=\"cc\" class=\"easyui-layout\" style=\"width:100%;height:100%;\" data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-1\" data-genuitec-path=\"/Hydropower_query_system/WebRoot/HydropowerQueryMaintenance.jsp\">\r\n");
      out.write("\t    <div id=\"form1\" data-options=\"region:'north'\" style=\"width:110%;height:80px;\">\r\n");
      out.write("\t       <input id=\"year\" name=\"Year\">\r\n");
      out.write("\t\t\t    <input id=\"season\" class=\"easyui-combobox\" name=\"season\" data-options=\"\r\n");
      out.write("\t\t\t    prompt:'季度',\r\n");
      out.write("\t\t\t\tvalueField: 'label',\r\n");
      out.write("\t\t\t\ttextField: 'value',\r\n");
      out.write("\t\t\t\tdata: [{\r\n");
      out.write("\t\t\t\t\tlabel: '第1季度',\r\n");
      out.write("\t\t\t\t\tvalue: '第1季度'\r\n");
      out.write("\t\t\t\t},{\r\n");
      out.write("\t\t\t\t\tlabel: '第2季度',\r\n");
      out.write("\t\t\t\t\tvalue: '第2季度'\r\n");
      out.write("\t\t\t\t},{\r\n");
      out.write("\t\t\t\t\tlabel: '第3季度',\r\n");
      out.write("\t\t\t\t\tvalue: '第3季度'\r\n");
      out.write("\t\t\t\t},{\r\n");
      out.write("\t\t\t\t\tlabel: '第4季度',\r\n");
      out.write("\t\t\t\t\tvalue: '第4季度'\r\n");
      out.write("\t\t\t\t}]\"/>\r\n");
      out.write("\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t <input id=\"name1\" class=\"easyui-textbox\" prompt='姓名' name=\"name1\">\r\n");
      out.write("\t\t\t\t  <input id=\"id1\" class=\"easyui-textbox\" prompt='序号' name=\"id1\">\r\n");
      out.write("\t\t\t\t   <input id=\"salaryNum\" class=\"easyui-textbox\" prompt='工资号' name=\"salaryNum\">\r\n");
      out.write("\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t <input id=\"building\" name=\"building\">\r\n");
      out.write("\t\t\t\t  <input id=\"unit\" name=\"unit\">\r\n");
      out.write("\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t  <a href=\"javascript:void(0);\" class=\"easyui-linkbutton\" onclick=\"clear_data();\">清空</a>\r\n");
      out.write("\t\t\t\t<a href=\"javascript:void(0);\" class=\"easyui-linkbutton\" onclick=\"search_user();\">查询</a>\r\n");
      out.write("\t\t\t\t   <a id=\"btn\" href=\"#\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-add'\">新增</a>\r\n");
      out.write("\t\t\t\t    <a id=\"btn\" href=\"#\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-add'\">打印</a>\r\n");
      out.write("\t\t\t\t      <a id=\"btn\" href=\"#\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-add'\">统计</a>\r\n");
      out.write("\t\t\t\t         <a id=\"btn\" href=\"#\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-add'\">公告栏</a>\r\n");
      out.write("\t\t\t\t  \t    </div>\r\n");
      out.write("\t   \t \t<div data-options=\"region:'center'\">\r\n");
      out.write("\t\t\t\t\t <table id=\"datagrid\"></table>\r\n");
      out.write("\t        </div>\r\n");
      out.write("        </div>\r\n");
      out.write(" \t\t</div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
