/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.9
 * Generated at: 2019-10-30 11:19:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class deparment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "BaseJsp.jsp", out, false);
      out.write("\r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("  \r\n");
      out.write("  $(function()\r\n");
      out.write("  {\r\n");
      out.write("\t\t\r\n");
      out.write("  })\r\n");
      out.write("  lookRoles=function()\r\n");
      out.write("\t{\r\n");
      out.write("\t$('#pg').propertygrid({\r\n");
      out.write("\t    url: 'getAllDepartment.action',\r\n");
      out.write("\t    showGroup: true,\r\n");
      out.write("\t\tpagination:true,\r\n");
      out.write("\t\tpageSize:10,\r\n");
      out.write("\t\tpageList:[ 10,20,30,40],\r\n");
      out.write("\t\tfit:true,\r\n");
      out.write("\t    groupField : 'text',\r\n");
      out.write("\t    columns :[[\r\n");
      out.write("   \t\t    {field:'name',title:'角色ID',\r\n");
      out.write("   \t\t  formatter: function(value,row,index)\r\n");
      out.write("    \t\t{\r\n");
      out.write("    \t\t if (!row.roles.length && typeof(row.roles.length)!=\"undefined\" && row.roles.length!=0){\r\n");
      out.write("            \treturn '';\r\n");
      out.write("            \t}else\r\n");
      out.write("            \t{\r\n");
      out.write("            \tvar roleId=[];\r\n");
      out.write("            \t\t\tfor(var j=0;j<row.roles.length;j++)\r\n");
      out.write("            \t\t\t{     \r\n");
      out.write("            \t\t\t\troleId.push(row.roles[j].roleId);  \t\r\n");
      out.write("            \t\t\t}\r\n");
      out.write("\t \t\t\t return roleId;\r\n");
      out.write("            \t}\r\n");
      out.write("    \t\t},width:200,sortable:true},\r\n");
      out.write("   \t\t    {field:'value',title:'权限',\r\n");
      out.write("   \t\t    formatter :function(value,row,index)\r\n");
      out.write("    \t\t{\r\n");
      out.write("    \t\t if (!row.roles.length && typeof(row.roles.length)!=\"undefined\" && row.roles.length!=0){\r\n");
      out.write("            \treturn '';\r\n");
      out.write("            \t}else\r\n");
      out.write("            \t{\r\n");
      out.write("            \tvar name=[];\r\n");
      out.write("            \t\t\tfor(var j=0;j<row.roles.length;j++)\r\n");
      out.write("            \t\t\t{ \r\n");
      out.write("            \t\t\t  \tfor(var k=0;k<row.roles[j].permission.length;k++)\t\r\n");
      out.write("\t \t\t\t\t\t\t\t{\r\n");
      out.write("\t \t\t\t\t\t\t\tname.push(row.roles[j].permission[k].name);  \t\r\n");
      out.write("\t \t\t\t\t\t\t\t}\r\n");
      out.write("            \t\t\t}\r\n");
      out.write("\t \t\t\t\t\t\t\t return name;\r\n");
      out.write("            \t}\r\n");
      out.write("    \t\t},width:200,sortable:true\r\n");
      out.write("    \t\t}\r\n");
      out.write("\t     ]\r\n");
      out.write("        ],\r\n");
      out.write("             toolbar:[{\r\n");
      out.write("\t\t\t     \t text:'返回',\r\n");
      out.write("\t\t\t     \t iconCls:'icon-undo',\r\n");
      out.write("\t\t\t     \t handler:function(){\r\n");
      out.write("\t\t\t     \t  $('#p').panel('open',true);\r\n");
      out.write("\t\t\t     \t $('#p_g').panel('close',true);\r\n");
      out.write("\t\t\t     \t $('#tg').treegrid('load',{});\r\n");
      out.write("\t\t\t     \t }\r\n");
      out.write("     \t }],\r\n");
      out.write("\t    scrollbarSize: 0 \r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\t\r\n");
      out.write("  \r\n");
      out.write("   lookUsers=function()\r\n");
      out.write("\t{\r\n");
      out.write("\t$('#pg1').propertygrid({\r\n");
      out.write("\t    url: 'getUserByDepartment.action',\r\n");
      out.write("\t    showGroup: true,\r\n");
      out.write("\t\tpagination:true,\r\n");
      out.write("\t\tpageSize:10,\r\n");
      out.write("\t\tchecked : true,\r\n");
      out.write("\t\tpageList:[ 10,20,30,40],\r\n");
      out.write("\t\tfit:true,\r\n");
      out.write("\t    groupField : 'text',\r\n");
      out.write("\t    groupFormatter : function(group,rows)\r\n");
      out.write("\t    {\r\n");
      out.write("\t    for(i=0;i<rows.length;i++)\r\n");
      out.write("\t    {\r\n");
      out.write("\t    return rows[i].department.name;\r\n");
      out.write("\t    }\r\n");
      out.write("\t    },\r\n");
      out.write("\t    columns :[[\r\n");
      out.write("   \t\t    {field:'userid',title:'用户编号',width:200,sortable:true},\r\n");
      out.write("   \t\t    {field:'realName',title:'真实姓名',width:200,sortable:true\r\n");
      out.write("    \t\t},\r\n");
      out.write("   \t\t    {field:'sex',title:'性别',width:200,sortable:true\r\n");
      out.write("    \t\t},\r\n");
      out.write("   \t\t    {field:'birthday',title:'出生日期',width:200,sortable:true\r\n");
      out.write("    \t\t},\r\n");
      out.write("   \t\t    {field:'job',title:'职务',width:200,sortable:true\r\n");
      out.write("    \t\t},\r\n");
      out.write("   \t\t    {field:'PINCodes',title:'身份证号',width:200,sortable:true\r\n");
      out.write("    \t\t},\r\n");
      out.write("   \t\t    {field:'telephone',title:'联系电话',width:200,sortable:true\r\n");
      out.write("    \t\t},\r\n");
      out.write("   \t\t    {field:'fixedPhone',title:'固定电话',width:200,sortable:true\r\n");
      out.write("    \t\t}\r\n");
      out.write("\t     ]\r\n");
      out.write("        ],\r\n");
      out.write("            toolbar:[{\r\n");
      out.write("\t\t\t     \t text:'返回',\r\n");
      out.write("\t\t\t     \t iconCls:'icon-undo',\r\n");
      out.write("\t\t\t     \t handler:function(){\r\n");
      out.write("\t\t\t     \t  $('#p').panel('open',true);\r\n");
      out.write("\t\t\t     \t $('#p_g').panel('open',true);\r\n");
      out.write("\t\t\t     \t $('#tg').treegrid('load',{});\r\n");
      out.write("\t\t\t     \t }\r\n");
      out.write("     \t }],\r\n");
      out.write("\t    scrollbarSize: 0 \r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\t\r\n");
      out.write("\t\tfunction edit(){\r\n");
      out.write("\t\t\t\tvar rows=$('#tg').datagrid('getSelections');\r\n");
      out.write("\t\t\t\tvar p;\r\n");
      out.write("\t\tif(rows.length == 1){\r\n");
      out.write("\t\t\tp=$('#dd').dialog({\r\n");
      out.write("  \t\t\ttitle : '修改部门',\r\n");
      out.write("  \t\t\thref : '',\r\n");
      out.write("  \t\t\twidth : 420,\r\n");
      out.write("  \t\t\theight : 380 ,\r\n");
      out.write("  \t\t\tbuttons: [{\r\n");
      out.write("  \t\t\t\ttext : '修改提交',\r\n");
      out.write("  \t\t\t\thandler : function()\r\n");
      out.write("  \t\t\t\t{\r\n");
      out.write("  \t\t\t\t\tvar f=$('#dd').find('form');\r\n");
      out.write("  \t\t\t\t\tf.form('submit',{\r\n");
      out.write("  \t\t\t\t\turl:'updateDepartment.action',\r\n");
      out.write("  \t\t\t\t\tsuccess : function(data)\r\n");
      out.write("  \t\t\t\t\t{\r\n");
      out.write("  \t\t\t\t\t\t\tconsole.info(data);\r\n");
      out.write("  \t\t\t\t\t\t$('#dd').dialog('close',true);\r\n");
      out.write("  \t\t\t\t\t\t $('#tg').treegrid('load',{});\r\n");
      out.write("  \t\t\t\t\t\t$('#tg').treegrid('unselectAll');\r\n");
      out.write("  \t\t\t\t\r\n");
      out.write("  \t\t\t\t\t\t$.messager.show({\r\n");
      out.write("\t\t\t\t\t\t\ttitle:'部门提示',\r\n");
      out.write("\t\t\t\t\t\t\tmsg:'修改部门信息成功',\r\n");
      out.write("\t\t\t\t\t\t\ttimeout:5000,\r\n");
      out.write("\t\t\t\t\t\t\tshowType:'slide'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("  \t\t\t\t\t},\r\n");
      out.write("  \t\t\t\t\tonLoadError : function()\r\n");
      out.write("  \t\t\t\t\t{\r\n");
      out.write("  \t\t\t\t\t\t$('#dd').dialog('close',true);\r\n");
      out.write("  \t\t\t\t\t\t$('#tg').treegrid('unselectAll');\r\n");
      out.write("  \t\t\t\t\t\t$.messager.show({\r\n");
      out.write("\t\t\t\t\t\t\ttitle:'部门提示',\r\n");
      out.write("\t\t\t\t\t\t\tmsg:'修改部门信息失败，请重新尝试',\r\n");
      out.write("\t\t\t\t\t\t\ttimeout:5000,\r\n");
      out.write("\t\t\t\t\t\t\tshowType:'slide'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("  \t\t\t\t\t}\r\n");
      out.write("  \t\t\t\t\t});\r\n");
      out.write("  \t\t\t\t}\r\n");
      out.write("  \t\t\t}],\r\n");
      out.write("  \t\t\tonOpen : function()\r\n");
      out.write("  \t\t\t{\r\n");
      out.write("  \t\t\t $(\"#ff\").form('clear');\r\n");
      out.write("\t\t\t\tconsole.info(rows[0]);\r\n");
      out.write("\t\t\tvar f=$('#ff').form();\r\n");
      out.write("\t\tvar parentDepartment = f.find('input[name=parentDepartment1]');\r\n");
      out.write("\t\tvar role = f.find('input[name=role]');\r\n");
      out.write("\t\t\t\t\t\t\t\t      parentDepartment.combobox({\r\n");
      out.write("\t\t\t\t\t\t\t\t    \t  prompt:'选择当前创建的父部门',\r\n");
      out.write("\t\t\t\t\t\t\t\t      \t\turl : 'getDepartment.action',\r\n");
      out.write("\t\t\t\t\t\t\t\t      \t\tvalueField :'number1',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t textField :'name',\r\n");
      out.write("\t\t\t\t\t\t\t\t      \t\tmode : 'remote',\r\n");
      out.write("\t\t\t\t\t\t\t\t      \t\thasDownArrow : true,\r\n");
      out.write("\t\t\t\t\t\t\t\t      \t\teditable : true,\r\n");
      out.write("\t\t\t\t\t\t\t\t      \t\tfilter : function(q, row){\r\n");
      out.write("                var opts = $(this).combobox('options');\r\n");
      out.write("                return row[opts.textField].indexOf(q) == 0;\t\r\n");
      out.write("           \t\t\t\t\t\t\t\t\t\t\t\t\t },\r\n");
      out.write("           \t\t\t\t\t\t\t\t\tonClick : function(record){\r\n");
      out.write("           \t\t\t\t\t\t\t\t\t\tconsole.info(record);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  role.combobox({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    \t  prompt:'创建子部门，子部门继承父部门角色，在此基础上增添当前创建的部门的权限',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      \t\turl : 'comboboxRoleByDepartment.action',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      \t\tvalueField :'number',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t textField :'roleId',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      \t\tmode : 'remote',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      \t\thasDownArrow : true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      \t\teditable : true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      \t\tmultiple : true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      \t\tqueryParams : {number1 : record.number1}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("           \t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t role.combobox({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    \t  prompt:'创建根部门，选择当前创建的部门的角色',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      \t\turl : 'comboboxRole.action',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      \t\tvalueField :'number',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t textField :'roleId',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      \t\tmode : 'remote',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      \t\thasDownArrow : true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      \t\teditable : true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      \t\tmultiple : true\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("  \t\t\t\r\n");
      out.write("  \t\t\tf.form('load',{\r\n");
      out.write("  \t\t\tname : rows[0].text,\r\n");
      out.write("  \t\t\theaderName : rows[0].attributes.headerName,\r\n");
      out.write("  \t\t\tofficeLocation : rows[0].attributes.officeLocation,\r\n");
      out.write("  \t\t\ttelephone : rows[0].attributes.telephone,\r\n");
      out.write("  \t\t\tnumber1 : rows[0].id,\r\n");
      out.write("  \t\t\tparentDepartment : rows[0]._parentId\r\n");
      out.write("  \t\t\t\t\t\t});\r\n");
      out.write("  \t\t\t}\r\n");
      out.write("  \t\t\t});\r\n");
      out.write("\t\t}else if(rows.length >1)\r\n");
      out.write("\t  \t{\r\n");
      out.write("\t  \t$.messager.alert('提示','同一时间只能编辑一条记录！','error');\r\n");
      out.write("\t  \t}else{\r\n");
      out.write("\t  \t\t$.messager.alert('提示','请勾选要编辑的记录！','error');\r\n");
      out.write("\t  \t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction save(){\r\n");
      out.write("\t\t\tif (editingId != undefined){\r\n");
      out.write("\t\t\t\tvar t = $('#tg');\r\n");
      out.write("\t\t\t\tt.treegrid('endEdit', editingId);\r\n");
      out.write("\t\t\t\teditingId = undefined;\r\n");
      out.write("\t\t\t\tvar rows=$('#tg').datagrid('getSelections');\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//递归删除\r\n");
      out.write("\t\tfunction panduan(rows,i,ids){\r\n");
      out.write("\t\tif(rows[i].children)\r\n");
      out.write("  \t\t\t\t\t{\r\n");
      out.write("\t\t\tfor(var j=0;j<rows[i].children.length;j++)\r\n");
      out.write("\t  \t\t\t\t\t{\r\n");
      out.write("\t  \t\t\t\t\tpanduan(rows[i].children,j,ids);\r\n");
      out.write("\t  \t\t\t\t\tids.push(rows[i].children[j].id);\r\n");
      out.write("\t  \t\t\t\t\t}\r\n");
      out.write("\t  \t\t\t}else{}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\tfunction cancel(){\r\n");
      out.write("\tvar rows = $('#tg').treegrid('getSelections');\r\n");
      out.write("\tconsole.info(rows);\r\n");
      out.write("  \tvar ids = [];\r\n");
      out.write("  \tif(rows.length > 0)\r\n");
      out.write("  \t{\r\n");
      out.write("  \t\t$.messager.confirm('请确认','您要删除当前所选部门？',function(r){\r\n");
      out.write("  \t\t\tif(r)\r\n");
      out.write("  \t\t\t{\r\n");
      out.write("  \t\t\t\tfor(var i=0;i<rows.length;i++)\r\n");
      out.write("  \t\t\t\t{\r\n");
      out.write("  \t\t\t\t\tids.push(rows[i].id);\r\n");
      out.write("\t  \t\t\t\tpanduan(rows,i,ids);\r\n");
      out.write("  \t\t\t\t}\r\n");
      out.write("  \t\t\t\t$.ajax({\r\n");
      out.write("  \t\t\t\t\turl : 'deleteDepartment.action',\r\n");
      out.write("  \t\t\t\t\tdata : {\r\n");
      out.write("  \t\t\t\t\t\tids : ids.join(',')\r\n");
      out.write("  \t\t\t\t\t},\r\n");
      out.write("  \t\t\t\t\tdataType : 'json',\r\n");
      out.write("  \t\t\t\t\tsuccess: function(d)\r\n");
      out.write("  \t\t\t\t\t{\r\n");
      out.write("  \t\t\t\t\t\t$('#tg').treegrid('unselectAll');\r\n");
      out.write("  \t\t\t\t\t\t$('#tg').treegrid('load',{});\r\n");
      out.write("  \t\t\t\t\t\t$.messager.show({\r\n");
      out.write("  \t\t\t\t\t\t\ttitle : '提示',\r\n");
      out.write("  \t\t\t\t\t\t\tmsg : d.msg\r\n");
      out.write("  \t\t\t\t\t\t});\r\n");
      out.write("  \t\t\t\t\t}\r\n");
      out.write("  \t\t\t\t});\r\n");
      out.write("  \t\t\t}\r\n");
      out.write("  \t\t});\r\n");
      out.write("  \t}else\r\n");
      out.write("  \t{\r\n");
      out.write("  \t\t$.messager.alert('提示','请勾选要删除的部门!','error');\r\n");
      out.write("  \t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t add_department=function(){ \r\n");
      out.write("\t\t\taddForm =$('#adddepartment').form();\r\n");
      out.write("\t\t if ($('#adddepartment').form('validate')) {\r\n");
      out.write("\t\t \t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t  url : 'insertDepartment.action',\r\n");
      out.write("\t\t\t\t\t  type : 'POST',\r\n");
      out.write("\t\t\t\t\t  data : $('#adddepartment').serializeObject(),\r\n");
      out.write("\t\t\t\t\t  dataType : \"json\",\r\n");
      out.write("\t\t\t\t\t  traditional:true,\r\n");
      out.write("\t\t\t\t\t  success : function(data) {\r\n");
      out.write("\t\t\t\t\t   $('#tg').treegrid('load',{});\r\n");
      out.write("\t\t\t\t\t\t\t\t$.messager.show({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttitle:'申请部门提示',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tmsg:'申请部门成功',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttimeout:5000,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tshowType:'slide'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t $('#adddepartment').form('clear');\r\n");
      out.write("\t\t\t\t\t\t $('#win').panel('close',true);\r\n");
      out.write("\t\t\t\t\t   },\r\n");
      out.write("\t\t\t\t\t   error : function (XMLHttpRequest, textStatus, errorThrown) {\r\n");
      out.write("\t\t\t\t\t  \t\t$.messager.show({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttitle:'申请部门提示',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tmsg:'申请部门失败',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttimeout:5000,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tshowType:'slide'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}),\r\n");
      out.write("\t\t\t\t\t\t\t\t$.messager.confirm({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttitle: '申请部门提示',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tmsg: '是否重新申请部门',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfn: function(r){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tif (r){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t $('#win').panel('close',false);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t   }\t\t  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t });\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t$.messager.alert({\r\n");
      out.write("\t\t\t\t\t\t\ttitle: '申报部门提示',\r\n");
      out.write("\t\t\t\t\t\t\tmsg: '填写相关信息格式不正确'\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("  <script>\"undefined\"==typeof CODE_LIVE&&(!function(e){var t={nonSecure:\"63900\",secure:\"63905\"},c={nonSecure:\"http://\",secure:\"https://\"},r={nonSecure:\"127.0.0.1\",secure:\"gapdebug.local.genuitec.com\"},n=\"https:\"===window.location.protocol?\"secure\":\"nonSecure\";script=e.createElement(\"script\"),script.type=\"text/javascript\",script.async=!0,script.src=c[n]+r[n]+\":\"+t[n]+\"/codelive-assets/bundle.js\",e.getElementsByTagName(\"head\")[0].appendChild(script)}(document),CODE_LIVE=!0);</script></head>\r\n");
      out.write(" <body class=\"easyui-layout\" data-options=\"fit:true\" data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-7\" data-genuitec-path=\"/hdquan3/WebRoot/deparment.jsp\">\r\n");
      out.write(" \r\n");
      out.write(" \t<div data-options=\"region:'center',border:false\" style=\"overflow:hidden;\" data-options=\"fit:true\" data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-7\" data-genuitec-path=\"/hdquan3/WebRoot/deparment.jsp\">\r\n");
      out.write(" \t<div id=\"p\" class=\"easyui-panel\">\r\n");
      out.write(" \t<table id=\"tg\" class=\"easyui-treegrid\" title=\"部门管理\" style=\"fit:true\"\r\n");
      out.write("\t\t\tdata-options=\"\r\n");
      out.write("\t\t\t\ticonCls: 'icon-ok',\r\n");
      out.write("\t\t\t\trownumbers: true,\r\n");
      out.write("\t\t\t\tanimate: true,\r\n");
      out.write("\t\t\t\tcollapsible: true,\r\n");
      out.write("\t\t\t\tfitColumns: false,\r\n");
      out.write("\t\t\t\turl: 'getAllDepartment.action',\r\n");
      out.write("\t\t\t\tmethod: 'get',\r\n");
      out.write("\t\t\t\tidField: 'id',\r\n");
      out.write("\t\t\t\ttreeField: 'text',\r\n");
      out.write("\t\t\t\tpagination: true,\r\n");
      out.write("\t\t\t\tpageSize: 8,\r\n");
      out.write("\t\t\t\tpageList: [2,5,10],\r\n");
      out.write("\t\t\t\tshowFooter: true,\r\n");
      out.write("\t\t\t\ttoolbar: [{\r\n");
      out.write("\t\t\t\t\t\t\ticonCls: 'icon-edit',\r\n");
      out.write("\t\t\t\t\t\t\thandler: function(){\r\n");
      out.write("\t\t\t\t\t\t\tedit();\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t},'-',{\r\n");
      out.write("\t\t\t\t\t\t\ticonCls: 'icon-cancel',\r\n");
      out.write("\t\t\t\t\t\t\thandler: function(){\r\n");
      out.write("\t\t\t\t\t\tcancel();\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t},'-',{\r\n");
      out.write("\t\t\t\t\t\t\ticonCls: 'icon-add',\r\n");
      out.write("\t\t\t\t\t\t\thandler: function(){\r\n");
      out.write("\t\t\t\t\t\t\tvar f=$('#adddepartment').form();\r\n");
      out.write("\t\t\t\t\t\t\tvar parentDepartment = f.find('input[name=parentDepartment]');\r\n");
      out.write("\t\t\t\t\t\t\t\tvar permission = f.find('input[name=permission]');\r\n");
      out.write("\t\t\t\t\t\t\t\t     $('#win').panel('open',true);\r\n");
      out.write("\t\t\t\t\t\t\t\t      parentDepartment.combobox({\r\n");
      out.write("\t\t\t\t\t\t\t\t    \t  prompt:'选择当前创建的父部门',\r\n");
      out.write("\t\t\t\t\t\t\t\t      \t\turl : 'getDepartment.action',\r\n");
      out.write("\t\t\t\t\t\t\t\t      \t\tvalueField :'number1',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t textField :'name',\r\n");
      out.write("\t\t\t\t\t\t\t\t      \t\tmode : 'remote',\r\n");
      out.write("\t\t\t\t\t\t\t\t      \t\thasDownArrow : true,\r\n");
      out.write("\t\t\t\t\t\t\t\t      \t\teditable : true,\r\n");
      out.write("\t\t\t\t\t\t\t\t      \t\tfilter : function(q, row){\r\n");
      out.write("                var opts = $(this).combobox('options');\r\n");
      out.write("                return row[opts.textField].indexOf(q) == 0;\t\r\n");
      out.write("           \t\t\t\t\t\t\t\t\t\t\t\t\t },\r\n");
      out.write("           \t\t\t\t\t\t\t\t\tonClick : function(record){\r\n");
      out.write("           \t\t\t\t\t\t\t\t\t\tconsole.info(record);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  permission.combobox({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    \t  prompt:'创建子部门，子部门继承父部门角色，在此基础上增添当前创建的部门的权限',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      \t\turl : 'comboboxRoleByDepartment.action',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      \t\tvalueField :'number',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t textField :'roleId',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  width : 550,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      \t\tmode : 'remote',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      \t\thasDownArrow : true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      \t\teditable : true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      \t\tmultiple : true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      \t\tqueryParams : {number1 : record.number1}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("           \t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t permission.combobox({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    \t  prompt:'创建根部门，选择当前创建的部门的角色',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      \t\turl : 'comboboxRole.action',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      \t\tvalueField :'number',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t textField :'roleId',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      \t\tmode : 'remote',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     \t\t width : 300,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      \t\thasDownArrow : true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      \t\teditable : true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      \t\tmultiple : true\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t \t\t}\r\n");
      out.write("\t\t\t\t\t\t},'-',{\r\n");
      out.write("\t\t\t\t\t\t\ticonCls: 'icon-man',\r\n");
      out.write("\t\t\t\t\t\t\thandler: function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t $('#p').panel('close',true);\r\n");
      out.write("\t\t\t     \t $('#p_g').panel('open',true);\r\n");
      out.write("\t\t\t     \t \t \t  $('#p_g1').panel('close',true);\r\n");
      out.write("\t\t\t\t\t\t\tlookRoles();\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t},'-',{\r\n");
      out.write("\t\t\t\t\t\t\ticonCls: 'icon-search',\r\n");
      out.write("\t\t\t\t\t\t\thandler: function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t $('#p').panel('close',true);\r\n");
      out.write("\t\t\t\t\t\t\t\t \t $('#p_g1').panel('open',true);\r\n");
      out.write("\t\t\t\t\t\t\t\t \t  $('#p_g').panel('close',true);\r\n");
      out.write("\t\t\t\t\t\t\tlookUsers();\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}]\r\n");
      out.write("\t\t\t\">\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'text',width:530,editor:'textbox'\">部门名称</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"\r\n");
      out.write("\t\t\t\tfield:'headerName',width:200,align:'right',editor:'textbox',\r\n");
      out.write("\t\t\t\tformatter: function(value,row,index){\r\n");
      out.write("\t\t\t\tif (!row.attributes && typeof(row.attributes)!='undefined' && row.attributes!=0){\r\n");
      out.write("            \treturn '';\r\n");
      out.write("            \t}else\r\n");
      out.write("            \t{return row.attributes.headerName;\r\n");
      out.write("            \t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\">负责人</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"\r\n");
      out.write("\t\t\t\tfield:'officeLocation',width:200,editor:'textbox',\r\n");
      out.write("\t\t\t\tformatter: function(value,row,index){\r\n");
      out.write("\t\t\t\tif (!row.attributes && typeof(row.attributes)!='undefined' && row.attributes!=0){\r\n");
      out.write("            \treturn '';\r\n");
      out.write("            \t}else\r\n");
      out.write("            \t{return row.attributes.officeLocation;\r\n");
      out.write("            \t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\">办公地点</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"\r\n");
      out.write("\t\t\t\tfield:'telephone',width:200,editor:'textbox',\r\n");
      out.write("\t\t\t\tformatter: function(value,row,index){\r\n");
      out.write("\t\t\t\tif (!row.attributes && typeof(row.attributes)!='undefined' && row.attributes!=0){\r\n");
      out.write("            \treturn '';\r\n");
      out.write("            \t}else\r\n");
      out.write("            \t{return row.attributes.telephone;\r\n");
      out.write("            \t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\">值班电话</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"p_g\" class=\"easyui-panel\" style=\"width:100%;height:100%\">\r\n");
      out.write("\t\t <table id=\"pg\" style=\"width:100%;height:100%\"></table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"p_g1\" class=\"easyui-panel\" style=\"width:100%;height:100%\">\r\n");
      out.write("\t\t <table id=\"pg1\" style=\"width:100%;height:100%\"></table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"win\" class=\"easyui-dialog\" title=\"addDepartment\" style=\"width:600px;height:400px\" closed='true'\r\n");
      out.write("\t   data-options=\"iconCls:'icon-save',modal:true\">\r\n");
      out.write("\t   <form id=\"adddepartment\">\r\n");
      out.write("\t   \t<table class=\"tableForm datagrid-toolbar\" style=\"width:100%;height:100%\">\r\n");
      out.write("\t   \t\r\n");
      out.write("\t\t\t<div style=\"margin-bottom:20px\">\r\n");
      out.write("\t\t\t\t\t<input class=\"easyui-textbox\" data-options=\"\r\n");
      out.write("\t\t\t\t\tlabel: '部门名称',\r\n");
      out.write("\t\t\t\t\tlabelPosition: 'top',\r\n");
      out.write("\t\t\t\t\tprompt: 'Input something here!',\r\n");
      out.write("\t\t\t\t\ticonWidth: 22,\r\n");
      out.write("\t\t\t\t\trequired : true,\r\n");
      out.write("\t\t\t\t\tvalidType : ['String','length[0,20]'],\r\n");
      out.write("\t\t\t\t\tmissingMessage :'部门名称不能为空',\r\n");
      out.write("\t\t\t\t\ticons: [{\r\n");
      out.write("\t\t\t\t\t\ticonCls:'icon-clear',\r\n");
      out.write("\t\t\t\t\t\thandler: function(e){\r\n");
      out.write("\t\t\t\t\t\t\t$(e.data.target).textbox('clear');\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}],\r\n");
      out.write("\t\t\t\t\ticonAlign:'right'\" \r\n");
      out.write("\t\t\t\t\tstyle=\"width:300px;width:100%;\" name=\"name\"/>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"margin-bottom:20px\">\r\n");
      out.write("\t\t\t<input class=\"easyui-textbox\" data-options=\"\r\n");
      out.write("\t\t\t\t\tlabel: '负责人',\r\n");
      out.write("\t\t\t\t\tlabelPosition: 'top',\r\n");
      out.write("\t\t\t\t\trequired : true,\r\n");
      out.write("\t\t\t\t\tvalidType : ['String','length[0,20]'],\r\n");
      out.write("\t\t\t\t\tmissingMessage :'请问负责人是哪位',\r\n");
      out.write("\t\t\t\t\tprompt: '',\r\n");
      out.write("\t\t\t\t\ticonWidth: 22,\r\n");
      out.write("\t\t\t\t\ticons: [{\r\n");
      out.write("\t\t\t\t\t\ticonCls:'icon-clear',\r\n");
      out.write("\t\t\t\t\t\thandler: function(e){\r\n");
      out.write("\t\t\t\t\t\t\t$(e.data.target).textbox('clear');\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}],\r\n");
      out.write("\t\t\t\t\ticonAlign:'right'\" \r\n");
      out.write("\t\t\t\t\tstyle=\"width:300px;width:100%;\" name=\"headerName\" id=\"headerName\"/>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"margin-bottom:20px\">\r\n");
      out.write("\t\t\t<input class=\"easyui-textbox\" data-options=\"\r\n");
      out.write("\t\t\t\t\tlabel: '办公地点',\r\n");
      out.write("\t\t\t\t\tlabelPosition: 'top',\r\n");
      out.write("\t\t\t\t\tprompt: '',\r\n");
      out.write("\t\t\t\t\ticonWidth: 22,\r\n");
      out.write("\t\t\t\t\trequired : true,\r\n");
      out.write("\t\t\t\t\tvalidType : ['String','length[0,20]'],\r\n");
      out.write("\t\t\t\t\tmissingMessage :'部门办公不能为空',\r\n");
      out.write("\t\t\t\t\ticons: [{\r\n");
      out.write("\t\t\t\t\t\ticonCls:'icon-clear',\r\n");
      out.write("\t\t\t\t\t\thandler: function(e){\r\n");
      out.write("\t\t\t\t\t\t\t$(e.data.target).textbox('clear');\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}],\r\n");
      out.write("\t\t\t\t\ticonAlign:'right'\" \r\n");
      out.write("\t\t\t\t\tstyle=\"width:300px;width:100%;\" name=\"officeLocation\" id=\"officeLocation\"/>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div style=\"margin-bottom:20px\">\r\n");
      out.write("\t\t\t<input class=\"easyui-textbox\" data-options=\"\r\n");
      out.write("\t\t\t\t\tlabel: '值班电话',\r\n");
      out.write("\t\t\t\t\tlabelPosition: 'top',\r\n");
      out.write("\t\t\t\t\tprompt: '',\r\n");
      out.write("\t\t\t\t\ticonWidth: 22,\r\n");
      out.write("\t\t\t\t\trequired : true,\r\n");
      out.write("\t\t\t\t\tvalidType : ['String','length[0,20]'],\r\n");
      out.write("\t\t\t\t\tmissingMessage :'值班电话不能为空',\r\n");
      out.write("\t\t\t\t\ticons: [{\r\n");
      out.write("\t\t\t\t\t\ticonCls:'icon-clear',\r\n");
      out.write("\t\t\t\t\t\thandler: function(e){\r\n");
      out.write("\t\t\t\t\t\t\t$(e.data.target).textbox('clear');\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}],\r\n");
      out.write("\t\t\t\t\ticonAlign:'right'\" \r\n");
      out.write("\t\t\t\t\tstyle=\"width:300px;width:100%;\" name=\"telephone\"/>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div style=\"margin-bottom:20px\">\r\n");
      out.write("\t\t\t<input id=\"parentDepartment\" label=\"选择父部门\" style=\"width:300px;width:100%;\" name=\"parentDepartment\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t      <label for=\"permission\">添加该部门拥有角色:</label>\r\n");
      out.write("\t\t       <input name=\"permission\" id=\"permission\"/>\r\n");
      out.write("\t\t   \t\t\t </div>\r\n");
      out.write("\t\t<div style=\"margin-bottom:20px\">\r\n");
      out.write("\t\t\t<input class=\"easyui-textbox\" label=\"Description:\" labelPosition=\"top\" multiline=\"true\" value=\"This TextBox will allow the user to enter multiple lines of text.\" style=\"width:100%;height:120px\" name=\"Description\" id=\"Description:\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<a href=\"#\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-ok'\"\r\n");
      out.write("        onclick=\"add_department();\">add_department</a>\r\n");
      out.write("        \t\t\t</table>\r\n");
      out.write("        </form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t <div id=\"dd\">\r\n");
      out.write("    <form id=\"ff\" method=\"post\">\r\n");
      out.write("    \t\t<div id=\"p\" class=\"easyui-panel\">\r\n");
      out.write("    \t\t <div>\r\n");
      out.write("\t\t    \t<div style=\"margin-bottom:20px\" align=\"center\">\r\n");
      out.write("\t\t        <label for=\"number1\">部门编号:</label>\r\n");
      out.write("\t\t        <input class=\"easyui-validatebox\" type=\"text\" editable=\"false\" name=\"number1\"/>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t   <div>\r\n");
      out.write("\t\t    \t<div style=\"margin-bottom:20px\" align=\"center\">\r\n");
      out.write("\t\t   \t\t  <label for=\"parentDepartment\">上级编号:</label>\r\n");
      out.write("\t\t        <input class=\"easyui-validatebox\" type=\"text\" editable=\"false\" name=\"parentDepartment\"/>\r\n");
      out.write("\t\t   \t\t </div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t </div>\r\n");
      out.write("\t\t    \t<div style=\"margin-bottom:20px\" align=\"center\">\r\n");
      out.write("\t\t        <label for=\"name\">部门名称:</label>\r\n");
      out.write("\t\t        <input class=\"easyui-validatebox\" type=\"text\" name=\"name\"/>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t    <div>\r\n");
      out.write("\t\t    \t<div style=\"margin-bottom:20px\" align=\"center\">\r\n");
      out.write("\t\t        <label for=\"headerName\">&nbsp;负责人:&nbsp;&nbsp;</label>\r\n");
      out.write("\t\t        <input class=\"easyui-validatebox\" type=\"text\" name=\"headerName\"/>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t     </div>\r\n");
      out.write("\t\t      <div>\r\n");
      out.write("\t\t      \t<div style=\"margin-bottom:20px\" align=\"center\">\r\n");
      out.write("\t\t        <label for=\"officeLocation\">办公地点:</label>\r\n");
      out.write("\t\t        <input class=\"easyui-validatebox\" type=\"text\" name=\"officeLocation\"/>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t    <div>\r\n");
      out.write("\t\t    \t<div style=\"margin-bottom:20px\" align=\"center\">\r\n");
      out.write("\t\t        <label for=\"telephone\">值班电话:</label>\r\n");
      out.write("\t\t        <input class=\"easyui-validatebox\" type=\"text\" name=\"telephone\"/>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t      <div>\r\n");
      out.write("\t\t    \t<div style=\"margin-bottom:20px\" align=\"center\">\r\n");
      out.write("\t\t        <label for=\"parentDepartment1\">选择父部门:</label>\r\n");
      out.write("\t\t        <input class=\"easyui-validatebox\" type=\"text\" name=\"parentDepartment1\"/>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t    <div>\r\n");
      out.write("\t\t    \t<div style=\"margin-bottom:20px\" align=\"center\">\r\n");
      out.write("\t\t      <label for=\"role\">修改该部门拥有角色:</label>\r\n");
      out.write("\t\t       <input class=\"easyui-validatebox\" type=\"text\" name=\"role\" id=\"role\"/>\r\n");
      out.write("\t\t     </div>\r\n");
      out.write("\t\t   \t </div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("    </div>\r\n");
      out.write("   </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
