/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.9
 * Generated at: 2019-10-30 11:19:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    ");

	String url = request.getRequestURL().toString();
	url = url.substring(0, url.indexOf('/', url.indexOf("//") + 2));
	String context = request.getContextPath();
	url += context;
	application.setAttribute("ctx", url);
	String loginName = request.getParameter("username");
	String password = request.getParameter("password");
	System.out.println(loginName+"xxx"+password);

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"content-type\" content=\"text/html;\" charset=\"UTF-8\">\r\n");
      out.write("  \t<script type=\"text/javascript\" src=\"js/jquery-easyui-1.8.2/jquery.min.js\" charset=\"uft-8\"></script> \r\n");
      out.write("  \t<script type=\"text/javascript\" src=\"js/jquery-easyui-1.8.2/jquery.easyui.min.js\" charset=\"uft-8\"></script>\r\n");
      out.write("     <script type=\"text/javascript\" src=\"js/jquery-easyui-1.8.2/locale/easyui-lang-zh_CN.js\" charset=\"uft-8\"></script> \r\n");
      out.write("   <link rel=\"stylesheet\" href=\"js/jquery-easyui-1.8.2/themes/gray/easyui.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"js/jquery-easyui-1.8.2/themes/icon.css\" type=\"text/css\"> \r\n");
      out.write("    \r\n");
      out.write("  <script>\"undefined\"==typeof CODE_LIVE&&(!function(e){var t={nonSecure:\"63900\",secure:\"63905\"},c={nonSecure:\"http://\",secure:\"https://\"},r={nonSecure:\"127.0.0.1\",secure:\"gapdebug.local.genuitec.com\"},n=\"https:\"===window.location.protocol?\"secure\":\"nonSecure\";script=e.createElement(\"script\"),script.type=\"text/javascript\",script.async=!0,script.src=c[n]+r[n]+\":\"+t[n]+\"/codelive-assets/bundle.js\",e.getElementsByTagName(\"head\")[0].appendChild(script)}(document),CODE_LIVE=!0);</script></head>\r\n");
      out.write("  <body class=\"easyui-layout\" style=\"background-size: 100%;\" data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-774\" data-genuitec-path=\"/hdquan3/WebRoot/login.jsp\">\r\n");
      out.write("\t\t<div id=\"w\" class=\"easyui-window\" title=\"用户登录\" collapsible=\"false\"\r\n");
      out.write("\t\t\tminimizable=\"false\" maximizable=\"false\" icon=\"icon-save\"\r\n");
      out.write("\t\t\tstyle=\"width: 450px; height: 330px; padding: 30px; background: #fafafa;\"\r\n");
      out.write("\t\t\tdata-options=\"closable:false,draggable:false\" data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-774\" data-genuitec-path=\"/hdquan3/WebRoot/login.jsp\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<form id=\"formlogin\" method=\"post\" action=\"login.action\">\r\n");
      out.write("\t\t\t<!-- menulogin -->\r\n");
      out.write("\t\t\t\t<div style=\"margin-bottom: 20px\">\r\n");
      out.write("\t\t\t\t\t<input class=\"easyui-textbox\" id=\"username\" name=\"username\"\r\n");
      out.write("\t\t\t\t\t\tprompt=\"username\" iconWidth=\"28\" \r\n");
      out.write("\t\t\t\t\t\tdata-options=\"label:'用户名:',required:true\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 300px; height: 34px; padding: 10px;\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div style=\"margin-bottom: 20px\">\r\n");
      out.write("\t\t\t\t\t<input class=\"easyui-passwordbox\" id=\"password\" name=\"password\"\r\n");
      out.write("\t\t\t\t\t\tprompt=\"password\" iconWidth=\"28\"\r\n");
      out.write("\t\t\t\t\t\tdata-options=\"label:'密码:',required:true\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 300px; height: 34px; padding: 10px\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div style=\"margin-bottom: 20px\">\r\n");
      out.write("\t\t\t\t\t <input class=\"easyui-textbox\" id=\"captchaCode\" name=\"captchaCode\"\r\n");
      out.write("\t\t\t\t\t\tprompt=\"验证码\" iconWidth=\"28\"\r\n");
      out.write("\t\t\t\t\t\tdata-options=\"label:'验证码:',required:true,missingMessage:''\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 200px; height: 30px;\">\r\n");
      out.write("\t\t\t\t\t <img src=\"kaptcha.jpg\"/>\r\n");
      out.write("\t\t\t\t</div>  \r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" id=\"rememberMe\" name=\"rememberMe\">记住我\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<div style=\"text-align: center; padding: 5px 0\">\r\n");
      out.write("\t\t\t\t<a href=\"javascript:void(0)\" id=\"login-submit-btn\"\r\n");
      out.write("\t\t\t\t\tclass=\"easyui-linkbutton\" style=\"width: 80px\">登录</a>\r\n");
      out.write("\t\t\t\t<a href=\"javascript:void(0)\" class=\"easyui-linkbutton\"\r\n");
      out.write("\t\t\t\t\tonclick=\"clearForm()\" style=\"width: 80px\">清空</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("<script charset=\"utf-8\">\r\n");
      out.write("\t\t\t$(function(){ \r\n");
      out.write("\t\t\t\tif(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"!=\"\"){ \r\n");
      out.write("\t\t\t\t\t//$.messager.alert('提示',\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("\t\t\t\t\tvar showmsg=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\t\t\t\t\t$.messager.show({\r\n");
      out.write("\t\t\t\t\t\ttitle:'提示',\r\n");
      out.write("\t\t\t\t\t\tmsg:showmsg\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t/*获取焦点*/\r\n");
      out.write("\t\t\t\t$('#username').textbox('textbox').focus(); \r\n");
      out.write("\t\t\t\t/** 给登录按钮绑定点击事件  */\r\n");
      out.write("\t\t\t\t$(\"#login-submit-btn\").on(\"click\", function() {\r\n");
      out.write("\t\t\t\t\t/** 校验登录参数 ctrl+K */\r\n");
      out.write("\t\t\t\t\tvar username = $(\"#username\").val();\r\n");
      out.write("\t\t\t\t\tvar password = $(\"#password\").val();\r\n");
      out.write("\t\t\t\t\tvar captchaCode = $(\"#captchaCode\").val();\r\n");
      out.write("\t\t\t\t\t\tconsole.info(username);\r\n");
      out.write("\t\t\t\t\t\tif($(\"#formlogin\").form('validate')){\r\n");
      out.write("\t\t\t\t\t\tvar msg = \"\"; \r\n");
      out.write("\t\t\t\t\t\tif (!/^\\w{1,20}$/.test(username)) {\r\n");
      out.write("\t\t\t\t\t\t\tmsg = \"登录名长度必须是1~20之间\";\r\n");
      out.write("\t\t\t\t\t\t} else if (!/^\\w{1,20}$/.test(password)) {\r\n");
      out.write("\t\t\t\t\t\t\tmsg = \"密码长度必须是1~20之间\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif (msg != \"\") {\r\n");
      out.write("\t\t\t\t\t\t\t$.messager.alert('用户名密码错误',msg,'info');\r\n");
      out.write("\t\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t\t} \r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t$(\"#formlogin\").submit();\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t /** 按了回车键 */\r\n");
      out.write("\t\t\t\t$(document).keydown(function(event) {\r\n");
      out.write("\t\t\t\t\tif (event.keyCode == 13) {\r\n");
      out.write("\t\t\t\t\t\t$(\"#login-submit-btn\").trigger(\"click\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}); \r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\tfunction clearForm() {\r\n");
      out.write("\t\t\t\t$('#formlogin').form('clear');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
