/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.9
 * Generated at: 2019-10-30 11:19:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.shiro.web.subject.support.DefaultWebSubjectContext;
import java.util.*;

public final class north_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.apache.shiro.web.subject.support.DefaultWebSubjectContext");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\t\t\t\t");
Object use = session.getAttribute(DefaultWebSubjectContext.PRINCIPALS_SESSION_KEY);
				request.setAttribute("usename", use);
					
      out.write("\r\n");
      out.write(" \t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "BaseJsp.jsp", out, false);
      out.write("\t\t\t\t\t\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>My JSP 'north.jsp' starting page</title>\r\n");
      out.write("    \r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t \t <meta http-equiv=\"content-type\" content=\"text/html;\" charset=\"UTF-8\">\r\n");
      out.write("\t<!--\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\">\r\n");
      out.write("\t-->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar newdata=undefined;\r\n");
      out.write("\t\r\n");
      out.write("\t\t\tfunction User_logout(obj){\r\n");
      out.write("\t\tconsole.info(obj);\r\n");
      out.write("\t\tif(obj){\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\turl:\"logout.action\"\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\turl:\"logout.action\"\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\twindow.location.replace(\"login.jsp\")\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar usename=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${usename }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("\t\r\n");
      out.write("\t\tSeacher_UserInfo=function()\r\n");
      out.write("\t{\r\n");
      out.write("\t\t$.messager.progress();\t\r\n");
      out.write("\t var f=$('#dd').find('form');\r\n");
      out.write("\t\tf.form('submit', {\r\n");
      out.write("\t\t\turl: 'findUserByusercode.action',\r\n");
      out.write("\t\t\tqueryParams :{usename},\r\n");
      out.write("\t\t\tonSubmit: function(data){\r\n");
      out.write("\t\t\t\tvar isValid = $(this).form('validate');\r\n");
      out.write("\t\t\t\tif (!isValid){\r\n");
      out.write("\t\t\t\t\t$.messager.progress('close');\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\treturn isValid;\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\tconsole.info(usename);\r\n");
      out.write("\t\t\tnewdata=eval('(' + data + ')');\r\n");
      out.write("\t\t\t//console.info(newdata.rows[0]);\r\n");
      out.write("\t\t\tfor(var j=0;j<newdata.rows.length;j++)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\tconsole.info(newdata.rows[j]);\r\n");
      out.write("\t\t\t\tfor(var i=0;i<newdata.rows[j].roles.length;i++){\r\n");
      out.write("\t\t\tconsole.info(newdata.rows[j].roles[i].number);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\t$.messager.progress('close');\r\n");
      out.write("\t\t\t$('#dd').window('open');  \r\n");
      out.write("\t\t\t\t\t\tf.form('load',{\r\n");
      out.write("  \t\t\t\t\t\t\tuserid : newdata.rows[0].attributes.user.userid,\r\n");
      out.write("  \t\t\t\t\t\t\tusercode :newdata.rows[0].attributes.user.usercode,\r\n");
      out.write("  \t\t\t\t\t\t\trealName :newdata.rows[0].attributes.user.realName,\r\n");
      out.write("  \t\t\t\t\t\t\tjob :newdata.rows[0].attributes.user.job,\r\n");
      out.write("  \t\t\t\t\t\t\tPINCodes :newdata.rows[0].attributes.user.PINCodes,\r\n");
      out.write("  \t\t\t\t\t\t\ttelephone :newdata.rows[0].attributes.user.telephone,\r\n");
      out.write("  \t\t\t\t\t\t\tfixedPhone :newdata.rows[0].attributes.user.fixedPhone,\r\n");
      out.write("  \t\t\t\t\t\t\tPostalCode :newdata.rows[0].attributes.user.PostalCode,\r\n");
      out.write("  \t\t\t\t\t\t\teMail :newdata.rows[0].attributes.user.eMail,\r\n");
      out.write("  \t\t\t\t\t\t\tQQ :newdata.rows[0].attributes.user.QQ,\r\n");
      out.write("  \t\t\t\t\t\t\tMSN :newdata.rows[0].attributes.user.MSN,\r\n");
      out.write("  \t\t\t\t\t\t\tPostalAddress :newdata.rows[0].attributes.user.PostalAddress\r\n");
      out.write("  \t\t\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tSeacher_UserGroup=function()\r\n");
      out.write("\t{\r\n");
      out.write("\t\t$('#pp').window('open');  \r\n");
      out.write("\t$('#pg').datagrid({\r\n");
      out.write("\t\turl: 'findUserByusercode.action',\r\n");
      out.write("\t\tqueryParams :{usename},\r\n");
      out.write("\t\t    pagination:true,\r\n");
      out.write("\t\t\tpageSize:10,\r\n");
      out.write("\t\t\tpageList:[ 10,20,30,40],\r\n");
      out.write("\t\t\tfit:true,\r\n");
      out.write("\t\t\tfitColums:false,\r\n");
      out.write("\t\t\tnowarp:false,\r\n");
      out.write("\t\t\tborder:false,\r\n");
      out.write("\t\t\tidField:'usGId',\r\n");
      out.write("\t\t    columns:[[\r\n");
      out.write("\t\t    {field:'usGId',title:'用户组编号',\r\n");
      out.write("\t\t      \t\t formatter: function(value,row,index)\r\n");
      out.write("    \t\t{\r\n");
      out.write("    \t\t if (!row.length && typeof(row.length)!=\"undefined\" && row.length!=0){\r\n");
      out.write("            \treturn '';\r\n");
      out.write("            \t}else{\r\n");
      out.write("    \t\t\treturn row.id;\r\n");
      out.write("            \t}\r\n");
      out.write("    \t\t},width:200,sortable:true,editor:{type:'textbox'}},\r\n");
      out.write("\t\t        {field:'leaderName',title:'创建者',\r\n");
      out.write("\t\t       formatter: function(value,row,index)\r\n");
      out.write("    \t\t{\r\n");
      out.write("    \t if (!row.length && typeof(row.length)!=\"undefined\" && row.length!=0){\r\n");
      out.write("            \treturn '';\r\n");
      out.write("            \t}else{\r\n");
      out.write("    \t\t\treturn row.attributes.leaderName;\r\n");
      out.write("            \t}\r\n");
      out.write("    \t\t},width:200,sortable:true,editor:{type:'textbox'}},\r\n");
      out.write("\t\t        {field:'time',title:'创建时间',\r\n");
      out.write("\t\t       \t\t formatter: function(value,row,index)\r\n");
      out.write("    \t\t{\r\n");
      out.write("    \t\t if (!row.length && typeof(row.length)!=\"undefined\" && row.length!=0){\r\n");
      out.write("            \treturn '';\r\n");
      out.write("            \t}else{\r\n");
      out.write("    \t\t\treturn row.attributes.time;\r\n");
      out.write("            \t}\r\n");
      out.write("    \t\t},width:200,sortable:true,editor:false},\r\n");
      out.write("\t\t        {field:'descipt',title:'用户组描述',\r\n");
      out.write("\t\t     \t\t formatter: function(value,row,index)\r\n");
      out.write("    \t\t{\r\n");
      out.write("    \t if (!row.length && typeof(row.length)!=\"undefined\" && row.length!=0){\r\n");
      out.write("            \treturn '';\r\n");
      out.write("            \t}else{\r\n");
      out.write("    \t\t\treturn row.attributes.descipt;\r\n");
      out.write("            \t}\r\n");
      out.write("    \t\t},width:200,sortable:true,editor:{type:'textbox'}},\r\n");
      out.write("\t\t    ]]\r\n");
      out.write("\t\t  \t})\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tSeacher_js=function(){\r\n");
      out.write("\t\t$('#qq').window('open');  \r\n");
      out.write("\tdatagridTojs=$('#datagrid').datagrid({\r\n");
      out.write("  \t\turl: 'findUserByusercode.action',\r\n");
      out.write("\t\ticonCls:'icon-save',\r\n");
      out.write("\t\tpagination:true,\r\n");
      out.write("\t\tpageSize:10,\r\n");
      out.write("\t\tpageList:[ 10,20,30,40],\r\n");
      out.write("\t\tfit:true,\r\n");
      out.write("\t\tfitColums:false,\r\n");
      out.write("\t\tnowarp:false,\r\n");
      out.write("\t\tborder:false,\r\n");
      out.write("\t\tidField:'number',\r\n");
      out.write("\t\tqueryParams : {\r\n");
      out.write("\t\t\t\tusename : usename,\r\n");
      out.write("\t\t\t\tseacher_role :true\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tfrozenColumns : [ [{\r\n");
      out.write("\t\t      field:'number',\r\n");
      out.write("\t\t     formatter : function(value,row,rowIndex)\r\n");
      out.write("            {\r\n");
      out.write("              if (!row.roles.length && typeof(row.roles.length)!=\"undefined\" && row.roles.length!=0){\r\n");
      out.write("            \treturn '';\r\n");
      out.write("            \t}else\r\n");
      out.write("            \t{        \r\n");
      out.write("            \t\tfor(var j=0;j<row.roles.length;j++)\r\n");
      out.write("            \t\t\t{    \r\n");
      out.write("            \treturn row.roles[j].number;\r\n");
      out.write("            \t\t\t}\r\n");
      out.write("            }\r\n");
      out.write("            },\r\n");
      out.write("            title:'编号',\r\n");
      out.write("            width:300,\r\n");
      out.write("            sortable:true,\r\n");
      out.write("            checkbox:true,\r\n");
      out.write("            align : 'center'\r\n");
      out.write("\t\t}]],\r\n");
      out.write("\t\t columns:[[\r\n");
      out.write("\t\t  {\r\n");
      out.write("            field:'roleId',\r\n");
      out.write("            formatter : function(value,row,rowIndex)\r\n");
      out.write("            {\r\n");
      out.write("                   if (!row.roles.length && typeof(row.roles.length)!=\"undefined\" && row.roles.length!=0){\r\n");
      out.write("            \treturn '';\r\n");
      out.write("            \t}else\r\n");
      out.write("            \t{      \r\n");
      out.write("            \tfor(var j=0;j<row.roles.length;j++)\r\n");
      out.write("            {  \r\n");
      out.write("            \treturn row.roles[j].roleId;\r\n");
      out.write("            \t\t\t}\r\n");
      out.write("            }\r\n");
      out.write("            },\r\n");
      out.write("            title:'角色ID',\r\n");
      out.write("            width:300,\r\n");
      out.write("            sortable:true,\r\n");
      out.write("            editor:{type:'validatebox',options:{required:true}},\r\n");
      out.write("            align : 'center'\r\n");
      out.write("            } , {\r\n");
      out.write("            field:'usGId',\r\n");
      out.write("            title:'用户组',\r\n");
      out.write("            width:100,\r\n");
      out.write("            align : 'center',\r\n");
      out.write("            formatter : function(value,row,rowIndex)\r\n");
      out.write("            {\r\n");
      out.write("\t            if (!row.roles.length && typeof(row.roles.length)!=\"undefined\" && row.roles.length!=0){\r\n");
      out.write("\t            \treturn '';\r\n");
      out.write("\t            \t}else\r\n");
      out.write("\t\t            \t{    \r\n");
      out.write("\t\t      \tfor(var j=0;j<row.roles.length;j++)\r\n");
      out.write("\t\t                   {  \r\n");
      out.write("\t\t                     if (!row.roles[j].userGroup && typeof(row.roles[j].userGroup)!=\"undefined\" && row.roles[j].userGroup!=0){\r\n");
      out.write("\t            \treturn '';\r\n");
      out.write("\t            \t}else\r\n");
      out.write("\t\t            \t{  \r\n");
      out.write("\t\t            \treturn row.roles[j].userGroup.usGId;\r\n");
      out.write("\t\t            \t}\r\n");
      out.write("\t\t            }\r\n");
      out.write("\t            }\r\n");
      out.write("            }\r\n");
      out.write("            } , {\r\n");
      out.write("            field:'name',\r\n");
      out.write("            title:'权限',\r\n");
      out.write("            width:100,\r\n");
      out.write("            align : 'center',\r\n");
      out.write("            formatter : function(value,row,rowIndex)\r\n");
      out.write("            {\r\n");
      out.write("  \t\t if (!row.roles.length && typeof(row.roles.length)!=\"undefined\" && row.roles.length!=0){\r\n");
      out.write("            \treturn '';\r\n");
      out.write("            \t}else\r\n");
      out.write("            \t{\r\n");
      out.write("       \tfor(var j=0;j<row.roles.length;j++)\r\n");
      out.write("            \t{  \r\n");
      out.write("      \t     if (!row.roles[j].permission && typeof(row.roles[j].permission)!=\"undefined\" && row.roles[j].permission!=0){\r\n");
      out.write("            \treturn '';\r\n");
      out.write("            \t}else\r\n");
      out.write("            \t{\r\n");
      out.write("\t \t\t\t\t  return row.roles[j].permission.name;\r\n");
      out.write("\t \t\t\t\t  }\r\n");
      out.write("            \t}\r\n");
      out.write("            }\r\n");
      out.write("            }\r\n");
      out.write("            }\r\n");
      out.write("\t\t ]]\r\n");
      out.write("\t\t })\r\n");
      out.write("}\r\n");
      out.write("var User_exclusive_attributes=undefined;\r\n");
      out.write("var UserGroup_exclusive_attributes=undefined;\r\n");
      out.write("User_Rejection_attribute=function(){\r\n");
      out.write("\t\tUser_exclusive_attributes=$('#Userexclusive').val();\r\n");
      out.write("\t\tconsole.info(User_exclusive_attributes);\r\n");
      out.write("\t\t$.ajax(\r\n");
      out.write("\t\t\t{ \r\n");
      out.write("\t\t\turl:\"User_Rejection_attribute.action\",\r\n");
      out.write("\t\t\tdata: {User_Rejection_attribute:User_exclusive_attributes}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("}\r\n");
      out.write("UserGroup_Rejection_attribute=function(){\r\n");
      out.write("\t\tUserGroup_exclusive_attributes=$('#UserGroupexclusive').val();\r\n");
      out.write("\t\tconsole.info(UserGroup_exclusive_attributes);\r\n");
      out.write("\t\t$.ajax(\r\n");
      out.write("\t\t\t{ \r\n");
      out.write("\t\t\turl:\"UserGroup_Rejection_attribute.action\",\r\n");
      out.write("\t\t\tdata: {UserGroupExclusiveProperties:UserGroup_exclusive_attributes}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<script>\"undefined\"==typeof CODE_LIVE&&(!function(e){var t={nonSecure:\"63900\",secure:\"63905\"},c={nonSecure:\"http://\",secure:\"https://\"},r={nonSecure:\"127.0.0.1\",secure:\"gapdebug.local.genuitec.com\"},n=\"https:\"===window.location.protocol?\"secure\":\"nonSecure\";script=e.createElement(\"script\"),script.type=\"text/javascript\",script.async=!0,script.src=c[n]+r[n]+\":\"+t[n]+\"/codelive-assets/bundle.js\",e.getElementsByTagName(\"head\")[0].appendChild(script)}(document),CODE_LIVE=!0);</script></head>\r\n");
      out.write("  \r\n");
      out.write("  <body data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-776\" data-genuitec-path=\"/hdquan3/WebRoot/north.jsp\">\r\n");
      out.write("  <div style=\"position:absolute; left:0px; buttom:0px;\" data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-776\" data-genuitec-path=\"/hdquan3/WebRoot/north.jsp\">\r\n");
      out.write("当前用户账号：");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${usename }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("  <div style=\"position:absolute; right:0px; buttom:0px;\">\r\n");
      out.write("  \t<a href=\"javascript:void(0);\" class=\"easyui-menubutton\" menu=\"#layout_north_kzmbMenu\" iconCls=\"icon-help\">控制面板</a>\r\n");
      out.write(" \t<a href=\"javascript:void(0);\" class=\"easyui-menubutton\" menu=\"#layout_north_zxMenu\" iconCls=\"icon-help\">系统面板</a>\r\n");
      out.write(" \t<a href=\"javascript:void(0);\" class=\"easyui-menubutton\" menu=\"#layout_north_upMenu\" iconCls=\"icon-danger\">用户排他属性面板</a>\r\n");
      out.write(" \t<a href=\"javascript:void(0);\" class=\"easyui-menubutton\" menu=\"#layout_north_downMenu\" iconCls=\"icon-danger\">用户组排他属性面板</a>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div id=\"layout_north_kzmbMenu\" style=\"width:100px; display:none;\">\r\n");
      out.write("  \t<div onclick=\"Seacher_UserInfo();\">个人信息</div>\r\n");
      out.write("  </div>\r\n");
      out.write("   <div id=\"layout_north_upMenu\" style=\"width:110px; display:none;\">\r\n");
      out.write("  \t\t\t<div> <label>排他角色roleID:</label></div>\t\r\n");
      out.write("\t\t     <input id=\"Userexclusive\" class=\"easyui-textbox\" name=\"User_exclusive_attributes\" style=\"width:100px\">\r\n");
      out.write("  \t\t\t<div onclick=\"User_Rejection_attribute();\"><button>提交</button></div>\r\n");
      out.write("   </div>\r\n");
      out.write("      <div id=\"layout_north_downMenu\" style=\"width:110px; display:none;\">\r\n");
      out.write("  \t\t\t<div> <label>排他角色roleID:</label></div>\t\r\n");
      out.write("\t\t     <input id=\"UserGroupexclusive\" class=\"easyui-textbox\" name=\"UserGroup_exclusive_attributes\" style=\"width:100px\">\r\n");
      out.write("  \t\t\t<div onclick=\"UserGroup_Rejection_attribute();\"><button>提交</button></div>\r\n");
      out.write("   </div>\r\n");
      out.write("  <!-- onclick=\"loginAndRegDialog.dialog('open');\" -->\r\n");
      out.write("  <div id=\"layout_north_zxMenu\" style=\"width:100px; display:none;\">\r\n");
      out.write("\t\t <div onclick=\"User_logout(false);\">重新登录</div>\r\n");
      out.write("\t\t \t \t<div onclick=\"User_logout(true);\">退出系统</div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <div id=\"dd\" class=\"easyui-dialog\" title=\"UserInfo\" style=\"width:600px;height:400px\" closed='true'\r\n");
      out.write("\t   data-options=\"iconCls:'icon-search',modal:true\">\r\n");
      out.write("     <form id=\"ff\" method=\"post\">\r\n");
      out.write("     <h1>个人信息</h1>\r\n");
      out.write("   \t\t\t  <a id=\"btn\" onclick=\"Seacher_UserGroup();\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-search'\">查询用户组</a>\r\n");
      out.write("       <a id=\"btn\" onclick=\"Seacher_js();\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-search'\">查询角色</a>\r\n");
      out.write("    \t\t <div>\r\n");
      out.write("\t\t    \t<div style=\"margin-bottom:20px\" align=\"center\">\r\n");
      out.write("\t\t        <label for=\"number1\">用户编号:</label>\r\n");
      out.write("\t\t        <input class=\"easyui-textbox\" name=\"userid\" style=\"width:100px\" readonly='true'>\r\n");
      out.write("\t\t     \r\n");
      out.write("\t\t        <label>登陆名:&nbsp;</label>\r\n");
      out.write("\t\t        <input class=\"easyui-textbox\" name=\"usercode\" style=\"width:100px\" readonly='true'>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t     <div>\r\n");
      out.write("\t\t    \t<div style=\"margin-bottom:20px\" align=\"center\">\r\n");
      out.write("\t\t        <label>真实姓名:</label>\r\n");
      out.write("\t\t        <input class=\"easyui-textbox\" name=\"realName\" style=\"width:100px\" readonly='true'>\r\n");
      out.write("\t\r\n");
      out.write("\t\t        <label>职务:&nbsp;&nbsp;&nbsp;&nbsp;</label>\r\n");
      out.write("\t\t        <input class=\"easyui-textbox\" name=\"job\" style=\"width:100px\" readonly='true'>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t     <div>\r\n");
      out.write("\t\t    \t<div style=\"margin-bottom:20px\" align=\"center\">\r\n");
      out.write("\t\t        <label>身份证号:</label>\r\n");
      out.write("\t\t        <input class=\"easyui-textbox\" name=\"PINCodes\" style=\"width:100px\" readonly='true'>\r\n");
      out.write("\r\n");
      out.write("\t\t        <label>联系电话:</label>\r\n");
      out.write("\t\t        <input class=\"easyui-textbox\" name=\"telephone\" style=\"width:100px\" readonly='true'>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t     <div>\r\n");
      out.write("\t\t    \t<div style=\"margin-bottom:20px\" align=\"center\">\r\n");
      out.write("\t\t        <label>固定电话:</label>\r\n");
      out.write("\t\t        <input class=\"easyui-textbox\" name=\"fixedPhone\" style=\"width:100px\" readonly='true'>\r\n");
      out.write("\t\r\n");
      out.write("\t\t        <label>邮政编码:</label>\r\n");
      out.write("\t\t        <input class=\"easyui-textbox\" name=\"PostalCode\" style=\"width:100px\" readonly='true'>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t     <div>\r\n");
      out.write("\t\t    \t<div style=\"margin-bottom:20px\" align=\"center\">\r\n");
      out.write("\t\t        <label>e-mail:</label>\r\n");
      out.write("\t\t        <input class=\"easyui-textbox\" name=\"eMail\" style=\"width:100px\" readonly='true'>\r\n");
      out.write("\r\n");
      out.write("\t\t        <label>QQ:&nbsp;</label>\r\n");
      out.write("\t\t        <input class=\"easyui-textbox\" name=\"QQ\" style=\"width:100px\" readonly='true'>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t     <div>\r\n");
      out.write("\t\t    \t<div style=\"margin-bottom:20px\" align=\"center\">\r\n");
      out.write("\t\t        <label>MSN:&nbsp;</label>\r\n");
      out.write("\t\t        <input class=\"easyui-textbox\" name=\"MSN\" style=\"width:100px\" readonly='true'>\r\n");
      out.write("\r\n");
      out.write("\t\t        <label>通邮地址:</label>\r\n");
      out.write("\t\t        <input class=\"easyui-textbox\" name=\"PostalAddress\" style=\"width:100px\" readonly='true'>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("\t\t\t<div id=\"pp\" class=\"easyui-dialog\" title=\"UserInfo\" style=\"width:600px;height:400px\" closed='true'\r\n");
      out.write("\t\t\t\t   data-options=\"iconCls:'icon-search',modal:true\">\r\n");
      out.write("\t\t\t <table id=\"pg\" style=\"fit:true\"></table>\r\n");
      out.write("\t\t\t </div>\r\n");
      out.write("\t\t\t \t<div id=\"qq\" class=\"easyui-dialog\" title=\"UserInfo\" style=\"width:600px;height:400px\" closed='true'\r\n");
      out.write("\t\t\t\t   data-options=\"iconCls:'icon-search',modal:true\">\r\n");
      out.write("\t\t\t <table id=\"datagrid\"></table>\r\n");
      out.write("\t\t\t \t </div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
