/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.9
 * Generated at: 2019-08-20 13:26:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class center_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "BaseJsp.jsp", out, false);
      out.write("\r\n");
      out.write("  <script>\"undefined\"==typeof CODE_LIVE&&(!function(e){var t={nonSecure:\"63900\",secure:\"63905\"},c={nonSecure:\"http://\",secure:\"https://\"},r={nonSecure:\"127.0.0.1\",secure:\"gapdebug.local.genuitec.com\"},n=\"https:\"===window.location.protocol?\"secure\":\"nonSecure\";script=e.createElement(\"script\"),script.type=\"text/javascript\",script.async=!0,script.src=c[n]+r[n]+\":\"+t[n]+\"/codelive-assets/bundle.js\",e.getElementsByTagName(\"head\")[0].appendChild(script)}(document),CODE_LIVE=!0);</script></head>\r\n");
      out.write("  <script type=\"text/javascript\" charset=\"utf-8\">\r\n");
      out.write("var datagrid;\r\n");
      out.write("var searchForm;\r\n");
      out.write("$(function(){\r\n");
      out.write("\tsearchForm=$('#user_search').form();\r\n");
      out.write("\teditRow = undefined;\r\n");
      out.write("\t\r\n");
      out.write("\tdatagrid=$('#datagrid').datagrid({\r\n");
      out.write("\t\t/* rowStyler: function(index,row){\r\n");
      out.write("\t\tif(row.realName == '大哥大')\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\treturn '';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn 'background-color:#6293BB;color:#fff;';\r\n");
      out.write("\t\t\t\t\t\t\t\t}, \r\n");
      out.write("\t\t*/\r\n");
      out.write("\t\turl:'user.action',\r\n");
      out.write("\t\ticonCls:'icon-save',\r\n");
      out.write("\t\tpagination:true,\r\n");
      out.write("\t\tpageSize:10,\r\n");
      out.write("\t\tpageList:[ 10,20,30,40],\r\n");
      out.write("\t\tfit:true,\r\n");
      out.write("\t\tfitColums:false,\r\n");
      out.write("\t\tnowarp:false,\r\n");
      out.write("\t\tborder:false,\r\n");
      out.write("\t\tidField:'userid',\r\n");
      out.write("\t\tsortName:'realName',\r\n");
      out.write("\t\tsortOrder:'asc',\r\n");
      out.write("\t\tfrozenColumns : [ [{\r\n");
      out.write("            field:'userid',\r\n");
      out.write("            title:'编号',\r\n");
      out.write("            width:100,\r\n");
      out.write("            sortable:true,\r\n");
      out.write("            checkbox:true,\r\n");
      out.write("            align : 'center'\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("            field:'realName',\r\n");
      out.write("            title:'姓名',\r\n");
      out.write("            width:100,\r\n");
      out.write("            sortable:true,\r\n");
      out.write("            editor:{type:'validatebox',options:{required:true}},\r\n");
      out.write("            align : 'center'\r\n");
      out.write("            }]],\r\n");
      out.write("\t\t columns:[[\r\n");
      out.write("           {\r\n");
      out.write("            field:'sex',\r\n");
      out.write("            title:'性别',\r\n");
      out.write("            width:100,\r\n");
      out.write("            sortable:true,\r\n");
      out.write("            editor:{type:'validatebox',options:{required:true}},\r\n");
      out.write("            align : 'center'\r\n");
      out.write("            },{\r\n");
      out.write("            field:'job',\r\n");
      out.write("            title:'工作',\r\n");
      out.write("            width:100,\r\n");
      out.write("            sortable:true,\r\n");
      out.write("            editor:{type:'validatebox',options:{required:true}},\r\n");
      out.write("            align : 'center'\r\n");
      out.write("            },{\r\n");
      out.write("            field:'PINCodes',\r\n");
      out.write("            title:'身份证号',\r\n");
      out.write("            width:100,\r\n");
      out.write("            sortable:true,\r\n");
      out.write("            editor:{type:'validatebox',options:{required:true}},\r\n");
      out.write("            align : 'center'\r\n");
      out.write("            },{\r\n");
      out.write("            field:'telephone',\r\n");
      out.write("            title:'联系电话',\r\n");
      out.write("            width:100,\r\n");
      out.write("            sortable:true,\r\n");
      out.write("            editor:{type:'validatebox'},\r\n");
      out.write("            align : 'center'\r\n");
      out.write("            },{\r\n");
      out.write("            field:'fixedPhone',\r\n");
      out.write("            title:'固定电话',\r\n");
      out.write("            width:100,\r\n");
      out.write("            sortable:true,\r\n");
      out.write("            editor:{type:'validatebox'},\r\n");
      out.write("            align : 'center'\r\n");
      out.write("            },{\r\n");
      out.write("            field:'eMail',\r\n");
      out.write("            title:'eMail',\r\n");
      out.write("            width:100,\r\n");
      out.write("            sortable:true,\r\n");
      out.write("            editor:{type:'validatebox'},\r\n");
      out.write("            align : 'center'\r\n");
      out.write("            },{\r\n");
      out.write("            field:'QQ',\r\n");
      out.write("            title:'QQ',\r\n");
      out.write("            width:100,\r\n");
      out.write("            sortable:true,\r\n");
      out.write("            editor:{type:'validatebox'},\r\n");
      out.write("            align : 'center'\r\n");
      out.write("            },{\r\n");
      out.write("            field:'MSN',\r\n");
      out.write("            title:'MSN',\r\n");
      out.write("            width:100,\r\n");
      out.write("            sortable:true,\r\n");
      out.write("            editor:{type:'validatebox'},\r\n");
      out.write("            align : 'center'\r\n");
      out.write("            },{\r\n");
      out.write("            field:'PostalAddress',\r\n");
      out.write("            title:'通邮地址',\r\n");
      out.write("            width:100,\r\n");
      out.write("            sortable:true,\r\n");
      out.write("            editor:{type:'validatebox'},\r\n");
      out.write("            align : 'center'\r\n");
      out.write("            },{\r\n");
      out.write("            field:'PostalCode',\r\n");
      out.write("            title:'邮政编码',\r\n");
      out.write("            width:100,\r\n");
      out.write("            sortable:true,\r\n");
      out.write("            editor:{type:'validatebox'},\r\n");
      out.write("            align : 'center'\r\n");
      out.write("            },{\r\n");
      out.write("            field:'usercode',\r\n");
      out.write("            title:'账号',\r\n");
      out.write("            width:100,\r\n");
      out.write("            sortable:true,\r\n");
      out.write("            editor:{type:'validatebox',options:{required:true}},\r\n");
      out.write("            align : 'center'\r\n");
      out.write("            },\r\n");
      out.write("            {field:'username',\r\n");
      out.write("            title:'密码',\r\n");
      out.write("            width:100,\r\n");
      out.write("            align:'center',\r\n");
      out.write("             editor:{type:'validatebox',options:{required:true}},\r\n");
      out.write("\t             formatter : function (value,row,index)\r\n");
      out.write("\t             {\r\n");
      out.write("\t            /*  return '<button>编辑</button><button>编辑</button>'; */\r\n");
      out.write("\t            \t return '******';\r\n");
      out.write("\t             } \r\n");
      out.write("            },\r\n");
      out.write("            {field:'birthday',\r\n");
      out.write("            title:'生日日期',\r\n");
      out.write("            width:100,\r\n");
      out.write("            align:'center',\r\n");
      out.write("             editor:{type:'datebox'}\r\n");
      out.write("              /*     时间格式化\r\n");
      out.write("              formatter : function (value,row,index)\r\n");
      out.write("\t             {\r\n");
      out.write("\t            \treturn new Date(value).format();//Date是javascript的\r\n");
      out.write("\t              } \r\n");
      out.write("\t          */\r\n");
      out.write("            },\r\n");
      out.write("            {field:'rolesIds',\r\n");
      out.write("            title:'所属角色',\r\n");
      out.write("            width:100,\r\n");
      out.write("            align : 'center',\r\n");
      out.write("                formatter : function (value,row,index)\r\n");
      out.write("\t             {\r\n");
      out.write("\t\t             if(row.roleNames){\r\n");
      out.write("\t\t              return sy.fs('<span title=\"{0}\">{1}</span>',row.roleNames,row.roleNames);\r\n");
      out.write("\t\t             }\r\n");
      out.write("\t             },\r\n");
      out.write("\t             editor : {\r\n");
      out.write("\t             \ttype : 'multiplecombobox',\r\n");
      out.write("\t             \toptions : {\r\n");
      out.write("\t             \t\turl : '',\r\n");
      out.write("\t             \t\tvalueField : 'cid',\r\n");
      out.write("\t             \t\ttextField : 'cname'\r\n");
      out.write("\t             \t\t}\r\n");
      out.write("\t          \t\t\t   }\r\n");
      out.write("            },{\r\n");
      out.write("            \tfield:'roleNames',\r\n");
      out.write("         \t   title:'所属角色',\r\n");
      out.write("         \t   width : 100,\r\n");
      out.write("         \t   hidden : true\r\n");
      out.write("            },\r\n");
      out.write("            {field:'controller',\r\n");
      out.write("            title:'控制列',\r\n");
      out.write("            width:100,\r\n");
      out.write("            align : 'center',\r\n");
      out.write("                formatter : function (value,row,index)\r\n");
      out.write("\t             {\r\n");
      out.write("\t              return '<button onclick=\"show('+index+');\">编辑</button><button>编辑</button>';\r\n");
      out.write("\t             }\r\n");
      out.write("            }\r\n");
      out.write("     \t\t\t   ]],\r\n");
      out.write("     \t toolbar:[{\r\n");
      out.write("     \t text:'增加',\r\n");
      out.write("     \t iconCls:'icon-add',\r\n");
      out.write("     \t handler:function(){\r\n");
      out.write("     \t \r\n");
      out.write("     \t/*  //在最底部追加一行\r\n");
      out.write("     \t datagrid.datagrid('appendRow',{\r\n");
      out.write("     \t\t\tuserid:'',\r\n");
      out.write("     \t\t\trealName:'',\r\n");
      out.write("     \t\t\tsex:'',\r\n");
      out.write("     \t\t\tbirthday:'',\r\n");
      out.write("     \t\t\tjob:'',\r\n");
      out.write("     \t\t\tPINCodes:'',\r\n");
      out.write("     \t\t\ttelephone:'',\r\n");
      out.write("     \t\t\tfixedPhone:'',\r\n");
      out.write("     \t\t\teMail:'',\r\n");
      out.write("     \t\t\tQQ:'',\r\n");
      out.write("     \t\t\tMSN:'',\r\n");
      out.write("     \t\t\tPostalAddress:'',\r\n");
      out.write("     \t\t\tPostalCode:''\r\n");
      out.write("     \t\t\t\t });\r\n");
      out.write("     \t\t\t\t var rows=datagrid.datagrid('getRows');\r\n");
      out.write("     \t\t\t\t datagrid.datagrid('beginEdit',rows.length-1);\t\r\n");
      out.write("     \t*/ \r\n");
      out.write("     \tif(editRow != undefined)\r\n");
      out.write("     \t{\r\n");
      out.write("     \tdatagrid.datagrid('endEdit',editRow);\r\n");
      out.write("     \t}\r\n");
      out.write("     \tif(editRow == undefined)\r\n");
      out.write("     \t{\r\n");
      out.write("     \t\r\n");
      out.write("     \tdatagrid.datagrid('addEditor',{\r\n");
      out.write("     \t\tfield:'username',\r\n");
      out.write("     \t\teditor:{\r\n");
      out.write("     \t\t\t   type:'validatebox',\r\n");
      out.write("     \t\t\t   options:{required:true}\r\n");
      out.write("     \t\t}\r\n");
      out.write("     \t});\r\n");
      out.write("     \t\r\n");
      out.write("   \t  datagrid.datagrid('insertRow',{\r\n");
      out.write("\t\t\t\tindex: 0,\t// index start with 0\r\n");
      out.write("\t\t\t\trow: {\r\n");
      out.write("\t\t\t\t\tuserid:uuid(),\r\n");
      out.write("\t     \t\t\trealName:'请输入您的真实姓名',\r\n");
      out.write("\t     \t\t\tsex:'',\r\n");
      out.write("\t     \t\t\tbirthday:'',\r\n");
      out.write("\t     \t\t\tjob:'',\r\n");
      out.write("\t     \t\t\tPINCodes:'',\r\n");
      out.write("\t     \t\t\ttelephone:'',\r\n");
      out.write("\t     \t\t\tfixedPhone:'',\r\n");
      out.write("\t     \t\t\teMail:'',\r\n");
      out.write("\t     \t\t\tQQ:'',\r\n");
      out.write("\t     \t\t\tMSN:'',\r\n");
      out.write("\t     \t\t\tPostalAddress:'',\r\n");
      out.write("\t     \t\t\tPostalCode:'',\r\n");
      out.write("\t     \t\t\tusercode:'',\r\n");
      out.write("\t     \t\t\tusername:''\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("     \t\t\tdatagrid.datagrid('beginEdit',0);\t\r\n");
      out.write("     \t\t\teditRow = 0;\r\n");
      out.write("     \t \t } \r\n");
      out.write("     \t }\r\n");
      out.write("     \t\t\t  },'-',{\r\n");
      out.write("     \t text:'删除',\r\n");
      out.write("     \t iconCls:'icon-remove',\r\n");
      out.write("     \t handler:function(){\r\n");
      out.write("     \t\tvar rows= datagrid.datagrid('getSelections');\r\n");
      out.write("     \t\tif(rows.length>0)\r\n");
      out.write("     \t\t{\r\n");
      out.write("     \t\t\t$.messager.confirm('请确认','您确定要删除当前所选择的项目吗？',function(b){\r\n");
      out.write("     \t\t\t\tif(b)\r\n");
      out.write("     \t\t\t\t{\r\n");
      out.write("     \t\t\t\tvar userids= [];\r\n");
      out.write("\t     \t\t\t\tfor(var i=0;i<rows.length;i++)\r\n");
      out.write("\t     \t\t\t\t{\r\n");
      out.write("\t     \t\t\t\t\tuserids.push(rows[i].userid)\r\n");
      out.write("\t     \t\t\t\t}\r\n");
      out.write("\t     \t\t\t\t$.ajax({\r\n");
      out.write("\t     \t\t\t\t\turl : 'deleteUser.action',\r\n");
      out.write("\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\tuserids : userids.join(',')\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\t\t\tsuccess : function(r)\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\tdatagrid.datagrid('load',{});\r\n");
      out.write("\t\t\t\tdatagrid.datagrid('unselectAll');\r\n");
      out.write("\t\t\t\t\t\t$.messager.show({\r\n");
      out.write("\t\t\t\t\t\ttitle:'提示',\r\n");
      out.write("\t\t\t\t\t\tmsg:'删除成功'\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t     \t\t\t\t})\r\n");
      out.write("     \t\t\t\t}\t\r\n");
      out.write("     \t\t\t\tconsole.info(userids.join(','));\r\n");
      out.write("     \t\t\t\r\n");
      out.write("     \t\t\t});\r\n");
      out.write("     \t\t}else{\r\n");
      out.write("     \t\t\t$.messager.alert('提示','请选择要删除的记录！','error');\r\n");
      out.write("     \t\t}\r\n");
      out.write("     \t\t\t\t }\r\n");
      out.write("     \t\t\t },'-',{\r\n");
      out.write("     \t text:'修改',\r\n");
      out.write("     \t iconCls:'icon-edit',\r\n");
      out.write("     \t handler:function(){\r\n");
      out.write("     \t\tvar rows= datagrid.datagrid('getSelections');\r\n");
      out.write("     \t\tif(rows.length==1)\r\n");
      out.write("     \t\t{\r\n");
      out.write("     \t\t\r\n");
      out.write("     \t\tdatagrid.datagrid('removeEditor','username');\r\n");
      out.write("     \t\t\r\n");
      out.write("\t\t     \t\tif(editRow != undefined)\r\n");
      out.write("\t\t     \t\t\t{\r\n");
      out.write("\t\t\t\t     \tdatagrid.datagrid('endEdit',editRow);\r\n");
      out.write("\t\t\t\t     \t}\r\n");
      out.write("\t\t\t\t     \tif(editRow == undefined)\r\n");
      out.write("\t\t\t\t     \t{\r\n");
      out.write("\t\t\t\t     \tvar index=datagrid.datagrid('getRowIndex',rows[0]);\t\r\n");
      out.write("\t\t\t \t\t\t\tdatagrid.datagrid('beginEdit',index);\t\r\n");
      out.write("\t\t\t     \t\t\teditRow = index;\r\n");
      out.write("\t\t\t     \t\t\tdatagrid.datagrid('unselectAll');\r\n");
      out.write("\t\t\t     \t \t } \r\n");
      out.write("     \t\t}\r\n");
      out.write("     \t\t\t \t\t\t}\r\n");
      out.write("     \t\t},'-',{\r\n");
      out.write("     \t text:'保存',\r\n");
      out.write("     \t iconCls:'icon-save',\r\n");
      out.write("     \t handler:function(){\r\n");
      out.write("     \t \tdatagrid.datagrid('endEdit',editRow);\r\n");
      out.write("     \t\t\t }\r\n");
      out.write("     \t\t},'-',{\r\n");
      out.write("     \t text:'取消编辑',\r\n");
      out.write("     \t iconCls:'icon-redo',\r\n");
      out.write("     \t handler:function(){\r\n");
      out.write("     \t \t\teditRow = undefined;\r\n");
      out.write("     \t \t\tdatagrid.datagrid('rejectChanges');//回滚\r\n");
      out.write("     \t \t\tdatagrid.datagrid('unselectAll');//撤销所选\r\n");
      out.write("     \t\t\t }\r\n");
      out.write("     \t\t},'-',{\r\n");
      out.write("     \t text:'取消选中',\r\n");
      out.write("     \t iconCls:'icon-redo',\r\n");
      out.write("     \t handler:function(){\r\n");
      out.write("     \t \t\teditRow = undefined;\r\n");
      out.write("     \t \t\tdatagrid.datagrid('unselectAll');//撤销所选\r\n");
      out.write("     \t\t\t }\r\n");
      out.write("     \t\t},'-',],\r\n");
      out.write("    \t onAfterEdit : function(index,row,changes)//注意是  ':'\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\tconsole.info(row);\r\n");
      out.write("\t\t\tvar inserted=datagrid.datagrid('getChanges','inserted');\r\n");
      out.write("\t\t\tvar updated=datagrid.datagrid('getChanges','updated');\r\n");
      out.write("\t\t\t//如果什么都没做，就不发ajax\r\n");
      out.write("\t\t\tif(inserted.length <1 && updated.length<1)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\teditRow = undefined;\r\n");
      out.write("     \t \t\tdatagrid.datagrid('unselectAll');\r\n");
      out.write("     \t \t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar url = '';\r\n");
      out.write("\t\t\tif(inserted.length>0)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\turl = 'insertUser.action';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(updated.length>0)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\turl = 'updateUser.action';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : url,\r\n");
      out.write("\t\t\t\t\tdata : row,\r\n");
      out.write("\t\t\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\t\t\tsuccess : function(r)\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tif(r && r.success)\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\tdatagrid.datagrid('acceptChanges');\r\n");
      out.write("\t\t\t\t\t\t\t$.messager.show({\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmsg : r.msg,\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle : '成功'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\tdatagrid.datagrid('rejectChanges');\r\n");
      out.write("\t\t\t\t\t\t\t$.messager.alert('错误',r.msg,'error');\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\teditRow = undefined;\r\n");
      out.write("\t\t\t\tdatagrid.datagrid('unselectAll');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\tonDblClickRow : function(index,row)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tdatagrid.datagrid('removeEditor','username');\r\n");
      out.write("\t\t\tif(editRow != undefined)\r\n");
      out.write("\t     \t{\r\n");
      out.write("\t     \tdatagrid.datagrid('endEdit',editRow);\r\n");
      out.write("\t     \t}\r\n");
      out.write("\t     \tif(editRow == undefined)\r\n");
      out.write("\t     \t{\r\n");
      out.write(" \t\t\t\tdatagrid.datagrid('beginEdit',index);\t\r\n");
      out.write("     \t\t\teditRow = index;\r\n");
      out.write("     \t \t } \r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tonRowContextMenu : function(e,index,row)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\te.preventDefault();//阻止游览器默认的事件\r\n");
      out.write("\t\t\t\t$(this).datagrid('unselectAll');//this代表当前的datagrid\r\n");
      out.write("\t\t\t\t$(this).datagrid('selectRow',index);\r\n");
      out.write("\t\t\t$('#menu').menu('show', {\r\n");
      out.write("\t\t\t\t\t\t\t    left: e.pageX,\r\n");
      out.write("\t\t\t\t\t\t\t    top: e.pageY\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//将表单的头部内容居中\r\n");
      out.write("\t\t$('.datagrid-header div').css('textAlign','center');\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\tfunction show(i)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tconsole.info(i);\r\n");
      out.write("\t\tvar rows = datagrid.datagrid('getRows'); \r\n");
      out.write("\t\t//console.info(rows);//当前页的所有行\r\n");
      out.write("\t\tconsole.info(rows[i]);//选择的哪一行\r\n");
      out.write("\t}\r\n");
      out.write("\t   \r\n");
      out.write("\tsearch_user=function ()\r\n");
      out.write("\t{\r\n");
      out.write("\tconsole.info(serializeObject(searchForm));\r\n");
      out.write("\t\t\t\t$('#datagrid').datagrid('load',\r\n");
      out.write("\t\t\t\t\t\t/* realName: $('#user_search').find('[name=realName]').val(),\r\n");
      out.write("\t\t\t\t\t\tbirthday:$('#user_search').find('[name=birthday]').val() */\r\n");
      out.write("\t\t\t\tserializeObject(searchForm)\r\n");
      out.write("\t\t\t\t\t);\r\n");
      out.write("\t}\r\n");
      out.write("\tclear_data=function()\r\n");
      out.write("\t{\r\n");
      out.write("\t$('#datagrid').datagrid('load',{});\r\n");
      out.write("\tsearchForm.find('input').val('');\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t/* edit_user= function() \r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar rows=$('#datagrid').datagrid('getSelections');\r\n");
      out.write("\t\tif(rows.length !=1&& rows.length !=0)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tvar  names=[];\r\n");
      out.write("\t\t\tfor(var i=0;i<rows.length;i++)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tnames.push(rows[i].name);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$.messager.show({\r\n");
      out.write("\t\t\t\tmsg:'只能选择一个用户进行编辑!您已经选择了【'+names.join(',')+'】'+rows.length+'个用户',\r\n");
      out.write("\t\t\t\ttitle:'提示'\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}else if(rows.length==1)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t//密码\r\n");
      out.write("\t\t\tuserForm.find('[name=username]').validatebox({\r\n");
      out.write("\t\t\t\trequired:false\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tuserForm.find('[name=name]').attr('readonly','readonly');\r\n");
      out.write("\t\tuserDialog.dialog('open');\r\n");
      out.write("\t\tuserForm.form('claer');\r\n");
      out.write("\t\tuserForm.form('load',{\r\n");
      out.write("\t\t\tuserid:rows[0].userid,\r\n");
      out.write("\t\t\trealName:rows[0].realName,\r\n");
      out.write("\t\t\tusername:'',\r\n");
      out.write("\t\t//\troleId:getList(rows[0].roleId)\t选择角色id\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}  */\r\n");
      out.write("</script>\r\n");
      out.write("  <body data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-4\" data-genuitec-path=\"/hdquan2/WebRoot/center.jsp\">\r\n");
      out.write("  <div class=\"easyui-layout\" fit=\"true\" border=\"false\" data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-4\" data-genuitec-path=\"/hdquan2/WebRoot/center.jsp\"> \r\n");
      out.write("\t<div region=\"north\" border=\"false\" title=\"查询条件\" style=\"height:180px;overflow:hidden;\">\r\n");
      out.write("\t\t<form id=\"user_search\">\r\n");
      out.write("\t\t\t<table class=\"tableForm datagrid-toolbar\" style=\"width:100%;height:100%\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>编号</th>\r\n");
      out.write("\t\t\t\t\t<td><input name=\"userid\"/></td>\r\n");
      out.write("\t\t\t\t\t<th>姓名</th>\r\n");
      out.write("\t\t\t\t\t<td><input name=\"realName\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>性别</th>\r\n");
      out.write("\t\t\t\t\t<td><input name=\"sex\"/></td>\r\n");
      out.write("\t\t\t\t\t\t<th>身份证号</th>\r\n");
      out.write("\t\t\t\t\t<td><input name=\"PINCodes\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>联系电话</th>\r\n");
      out.write("\t\t\t\t\t<td><input name=\"telephone\"/></td>\r\n");
      out.write("\t\t\t\t\t<th>固定电话</th>\r\n");
      out.write("\t\t\t\t\t<td><input name=\"fixedPhone\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>e-mail</th>\r\n");
      out.write("\t\t\t\t\t<td><input name=\"eMail\"/></td>\r\n");
      out.write("\t\t\t\t\t<th>QQ</th>\r\n");
      out.write("\t\t\t\t\t<td><input name=\"QQ\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>生日</th>\r\n");
      out.write("\t\t\t\t\t<td><input name=\"birthday\" class=\"easyui-datebox\" editable=\"false\" style=\"width:155px\"/>\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:void(0);\" class=\"easyui-linkbutton\" onclick=\"search_user();\">查询</a>\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:void(0);\" class=\"easyui-linkbutton\" onclick=\"clear_data();\">清空</a>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t<div region=\"center\" border=\"false\">\r\n");
      out.write("\t\t\t<table id=\"datagrid\"></table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"menu\" class=\"easyui-menu\" style=\"width:120px;display:none\">\r\n");
      out.write("\t\t\t<div onclick=\"append();\" iconCls=\"icon-add\">增加</div>\r\n");
      out.write("\t\t\t<div onclick=\"remove();\" iconCls=\"icon-remove\">删除</div>\r\n");
      out.write("\t\t\t<div onclick=\"edit_user();\" iconCls=\"icon-edit\">编辑</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("</div> \r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
