/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.9
 * Generated at: 2019-08-20 13:25:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class js_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "BaseJsp.jsp", out, false);
      out.write("\r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("  var datagridTojs;\r\n");
      out.write("var searchForm;\r\n");
      out.write("\r\n");
      out.write("  \t\t/* $('#cc').combotree({\r\n");
      out.write("\t\t    url: '',\r\n");
      out.write("\t\t\tcheckbox:true,\r\n");
      out.write("\t\t\tmultiple : true,\r\n");
      out.write("\t\t\tlines : true\r\n");
      out.write("\t\t\t}); */\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\r\n");
      out.write("\tdatagridTojs=$('#datagrid').datagrid({\r\n");
      out.write("  \t\turl:'role.action',\r\n");
      out.write("\t\ticonCls:'icon-save',\r\n");
      out.write("\t\tpagination:true,\r\n");
      out.write("\t\tpageSize:10,\r\n");
      out.write("\t\tpageList:[ 10,20,30,40],\r\n");
      out.write("\t\tfit:true,\r\n");
      out.write("\t\tfitColums:false,\r\n");
      out.write("\t\tnowarp:false,\r\n");
      out.write("\t\tborder:false,\r\n");
      out.write("\t\tidField:'userid',\r\n");
      out.write("\t\tqueryParams : {\r\n");
      out.write("\t\t\t\tallRole : 'true'\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tfrozenColumns : [ [{\r\n");
      out.write("\t\t      field:'number',\r\n");
      out.write("            title:'编号',\r\n");
      out.write("            width:300,\r\n");
      out.write("            sortable:true,\r\n");
      out.write("            checkbox:true,\r\n");
      out.write("            align : 'center'\r\n");
      out.write("\t\t}]],\r\n");
      out.write("\t\t columns:[[\r\n");
      out.write("\t\t  {\r\n");
      out.write("            field:'roleId',\r\n");
      out.write("            title:'角色ID',\r\n");
      out.write("            width:300,\r\n");
      out.write("            sortable:true,\r\n");
      out.write("            editor:{type:'validatebox',options:{required:true}},\r\n");
      out.write("            align : 'center'\r\n");
      out.write("            } , {\r\n");
      out.write("            field:'usGId',\r\n");
      out.write("            title:'用户组',\r\n");
      out.write("            width:100,\r\n");
      out.write("            align : 'center',\r\n");
      out.write("            formatter : function(value,rowData,rowIndex)\r\n");
      out.write("            {\r\n");
      out.write("            if (!rowData.userGroup && typeof(rowData.userGroup)!=\"undefined\" && rowData.userGroup!=0){\r\n");
      out.write("            \treturn '';\r\n");
      out.write("            \t}else\r\n");
      out.write("            \t{return rowData.userGroup.usGId;}\r\n");
      out.write("            }\r\n");
      out.write("            } , {\r\n");
      out.write("            field:'name',\r\n");
      out.write("            title:'权限',\r\n");
      out.write("            width:100,\r\n");
      out.write("            align : 'center',\r\n");
      out.write("            formatter : function(value,rowData,rowIndex)\r\n");
      out.write("            {\r\n");
      out.write("            if (!rowData.permission && typeof(rowData.permission)!=\"undefined\" && rowData.permission!=0){\r\n");
      out.write("            \treturn '';\r\n");
      out.write("            \t}else\r\n");
      out.write("            \t{\r\n");
      out.write("\t \t\t\t\t  return rowData.permission.name;\r\n");
      out.write("            \t\t\t}\r\n");
      out.write("            }\r\n");
      out.write("            }\r\n");
      out.write("\t\t ]],\r\n");
      out.write("\t\t toolbar : [{\r\n");
      out.write("     \t text:'增加',\r\n");
      out.write("     \t iconCls:'icon-add',\r\n");
      out.write("     \t handler:function(){\r\n");
      out.write("     \t \t\tappend();\r\n");
      out.write("     \t \t\t\t}\r\n");
      out.write("     \t},'-',{\r\n");
      out.write("     \t text:'删除',\r\n");
      out.write("     \t iconCls:'icon-remove',\r\n");
      out.write("     \t handler:function(){\r\n");
      out.write("     \t \t\tremove();\r\n");
      out.write("     \t \t\t\t}\r\n");
      out.write("     \t},'-',{\r\n");
      out.write("     \t text:'修改',\r\n");
      out.write("     \t iconCls:'icon-edit',\r\n");
      out.write("     \t handler:function(){\r\n");
      out.write("     \t \t\tedit();\r\n");
      out.write("     \t \t\t\t}\r\n");
      out.write("     \t},'-',{\r\n");
      out.write("     \t text:'我的角色',\r\n");
      out.write("     \t iconCls:'icon-edit',\r\n");
      out.write("     \t handler:function(){\r\n");
      out.write("     \t\t datagridTojs.datagrid({\r\n");
      out.write("     \t\t url:'role.action',\r\n");
      out.write("\t\ticonCls:'icon-save',\r\n");
      out.write("\t\tpagination:true,\r\n");
      out.write("\t\tpageSize:10,\r\n");
      out.write("\t\tpageList:[ 10,20,30,40],\r\n");
      out.write("\t\tfit:true,\r\n");
      out.write("\t\tfitColums:false,\r\n");
      out.write("\t\tnowarp:false,\r\n");
      out.write("\t\tborder:false,\r\n");
      out.write("\t\tqueryParams : {\r\n");
      out.write("\t\t\t\tallRole : 'false'\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tidField:'userid',\r\n");
      out.write("\t\tfrozenColumns : [ [{\r\n");
      out.write("\t\t      field:'number',\r\n");
      out.write("            title:'编号',\r\n");
      out.write("            width:300,\r\n");
      out.write("            sortable:true,\r\n");
      out.write("            checkbox:true,\r\n");
      out.write("            align : 'center'\r\n");
      out.write("\t\t}]],\r\n");
      out.write("\t\t columns:[[\r\n");
      out.write("\t\t  {\r\n");
      out.write("            field:'roleId',\r\n");
      out.write("            title:'角色ID',\r\n");
      out.write("            width:300,\r\n");
      out.write("            sortable:true,\r\n");
      out.write("            editor:{type:'validatebox',options:{required:true}},\r\n");
      out.write("            align : 'center'\r\n");
      out.write("            } , {\r\n");
      out.write("            field:'usGId',\r\n");
      out.write("            title:'用户组',\r\n");
      out.write("            width:100,\r\n");
      out.write("            align : 'center',\r\n");
      out.write("            formatter : function(value,rowData,rowIndex)\r\n");
      out.write("            {\r\n");
      out.write("            if (!rowData.userGroup && typeof(rowData.userGroup)!=\"undefined\" && rowData.userGroup!=0){\r\n");
      out.write("            \treturn '';\r\n");
      out.write("            \t}else\r\n");
      out.write("            \t{return rowData.userGroup.usGId;}\r\n");
      out.write("            }\r\n");
      out.write("            } , {\r\n");
      out.write("            field:'name',\r\n");
      out.write("            title:'权限',\r\n");
      out.write("            width:100,\r\n");
      out.write("            align : 'center',\r\n");
      out.write("            formatter : function(value,rowData,rowIndex)\r\n");
      out.write("            {\r\n");
      out.write("            if (!rowData.permission && typeof(rowData.permission)!=\"undefined\" && rowData.permission!=0){\r\n");
      out.write("            \treturn '';\r\n");
      out.write("            \t}else\r\n");
      out.write("            \t{\r\n");
      out.write("\t \t\t\t\t  return rowData.permission.name;\r\n");
      out.write("            \t\t\t}\r\n");
      out.write("            }\r\n");
      out.write("            }\r\n");
      out.write("\t\t ]],\r\n");
      out.write("     \t\t \r\n");
      out.write("     \t\t })\r\n");
      out.write("     \t \t\t/* $('#datagrid').datagrid('load',{\r\n");
      out.write("\t\t\t\t\t\t\tMyRoles: true\r\n");
      out.write("\t\t\t\t\t\t}); */\r\n");
      out.write("     \t \t\t\t}\r\n");
      out.write("     \t}\r\n");
      out.write("     \t],\r\n");
      out.write("     \tonLoadError :function(){\r\n");
      out.write("     \t$.messager.show({\r\n");
      out.write("\t\t\ttitle:'温馨提示',\r\n");
      out.write("\t\t\tmsg:'亲爱的客户，您没有查看角色的权限哦',\r\n");
      out.write("\t\t\ttimeout:5000,\r\n");
      out.write("\t\t\tshowType:'slide'\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("  \t\t\t});\r\n");
      out.write("  \t})\r\n");
      out.write("  \tfunction edit()\r\n");
      out.write("  \t{\r\n");
      out.write("  \t\tvar rows=datagridTojs.datagrid('getSelections');\r\n");
      out.write("  \t\tconsole.info(rows);\r\n");
      out.write("  \t\tif(rows.length == 1)\r\n");
      out.write("  \t\t{\r\n");
      out.write("  \t\t\tvar p=$('#dd').dialog({\r\n");
      out.write("  \t\t\t\ttitle: '编辑角色',\r\n");
      out.write("  \t\t\t\thref :'',\r\n");
      out.write("  \t\t\t\twidth : 420,\r\n");
      out.write("  \t\t\t\theight : 260,\r\n");
      out.write("  \t\t\t\tbuttons : [{\r\n");
      out.write("  \t\t\t\t\ttext : '编辑',\r\n");
      out.write("  \t\t\t\thandler : function()\r\n");
      out.write("  \t\t\t\t{\r\n");
      out.write("  \t\t\t\t\tvar f=p.find('form');\r\n");
      out.write("  \t\t\t\t\tf.form('submit',{\r\n");
      out.write("  \t\t\t\t\turl:'updateRole.action',\r\n");
      out.write("  \t\t\t\t\tsuccess : function(d)\r\n");
      out.write("  \t\t\t\t\t{\r\n");
      out.write("  \t\t\t\t\t\tif(d.success)\r\n");
      out.write("  \t\t\t\t\t\t{\r\n");
      out.write("  \t\t\t\t\t\tdatagridTojs.datagrid('reload');\r\n");
      out.write("  \t\t\t\t\t\tp.dialog('close');\r\n");
      out.write("  \t\t\t\t\t\t}\r\n");
      out.write("  \t\t\t\t\t\t$.messager.show({\r\n");
      out.write("  \t\t\t\t\t\t\tmsg : d.msg,\r\n");
      out.write("  \t\t\t\t\t\t\ttitle : '提示'\r\n");
      out.write("  \t\t\t\t\t\t}); \r\n");
      out.write("  \t\t\t\t\t}\r\n");
      out.write("  \t\t\t\t\t});\r\n");
      out.write("  \t\t\t\t}\r\n");
      out.write("  \t\t\t\t}],\r\n");
      out.write("  onOpen : function()\r\n");
      out.write("  \t{\r\n");
      out.write("  \t \t\t\r\n");
      out.write("  \t\tvar f=$('#dd').find('form');\r\n");
      out.write("  \t\tvar permission = f.find('input[name=permission]');\r\n");
      out.write("  \t\tvar permissionTree = permission.combotree({\r\n");
      out.write("\t\t\t\t  \ttextField: 'text',\r\n");
      out.write("\t\t\t\t    valueField: 'id',\r\n");
      out.write("\t\t\t\t    cascadeCheck : false,\r\n");
      out.write("  \t\t\t\t\tlines : true,\r\n");
      out.write("  \t\t\t\t\turl : 'permission.action',\r\n");
      out.write("  \t\t\t\t\tcheckbox : true,\r\n");
      out.write("  \t\t\t\t\tmultiple : true,\r\n");
      out.write("  \t\t\tonLoadSuccess : function()\r\n");
      out.write("  \t\t\t{\r\n");
      out.write("  \t\tpermissionTree.combotree('setValue', rows[0].permission.name);//有问题\r\n");
      out.write("  \t\tdatagridTojs.datagrid('unselectAll');\r\n");
      out.write("  \t\t\t}\r\n");
      out.write("  \t\t}); \r\n");
      out.write("  \t\tconsole.info(rows[0].permission.name);\r\n");
      out.write("  \t\tf.form('load',{\r\n");
      out.write("  \t\t\troleId : rows[0].roleId,\r\n");
      out.write("  \t\t\t/* cdesc : rows[0].cdesc,\r\n");
      out.write("  \t\t\tauthIds : getList(rows[0].authIds) */\r\n");
      out.write("  \t\t});\r\n");
      out.write("  \t\t\tpermissionTree.combotree('clear');\r\n");
      out.write("  \t}\r\n");
      out.write("  \t});\r\n");
      out.write("  \t}else if(rows.length >1)\r\n");
      out.write("  \t{\r\n");
      out.write("  \t$.messager.alert('提示','同一时间只能编辑一条记录！','error');\r\n");
      out.write("  \t}else{\r\n");
      out.write("  \t\t$.messager.alert('提示','请勾选要编辑的记录！','error');\r\n");
      out.write("  \t}\r\n");
      out.write("  \r\n");
      out.write("  \t\t\t}\r\n");
      out.write("  \t\r\n");
      out.write("  \tfunction append()\r\n");
      out.write("  \t{\r\n");
      out.write("  \t\tvar p=$('#dd').dialog({\r\n");
      out.write("  \t\t\ttitle : '添加角色',\r\n");
      out.write("  \t\t\thref : '',\r\n");
      out.write("  \t\t\twidth : 420,\r\n");
      out.write("  \t\t\theight : 260 ,\r\n");
      out.write("  \t\t\tbuttons: [{\r\n");
      out.write("  \t\t\t\ttext : '添加',\r\n");
      out.write("  \t\t\t\thandler : function()\r\n");
      out.write("  \t\t\t\t{\r\n");
      out.write("  \t\t\t\t\tvar f=p.find('form');\r\n");
      out.write("  \t\t\t\t\tf.form('submit',{\r\n");
      out.write("  \t\t\t\t\turl:'insertRole.action',\r\n");
      out.write("  \t\t\t\t\tsuccess : function(d)\r\n");
      out.write("  \t\t\t\t\t{\r\n");
      out.write("  \t\t\t\t\t\tif(d.success)\r\n");
      out.write("  \t\t\t\t\t\t{\r\n");
      out.write("  \t\t\t\t\t\tdatagridTojs.datagrid('reload');\r\n");
      out.write("  \t\t\t\t\t\tp.dialog('close');\r\n");
      out.write("  \t\t\t\t\t\t}\r\n");
      out.write("  \t\t\t\t\t\t$.messager.show({\r\n");
      out.write("  \t\t\t\t\t\t\tmsg : d.msg,\r\n");
      out.write("  \t\t\t\t\t\t\ttitle : '提示'\r\n");
      out.write("  \t\t\t\t\t\t}); \r\n");
      out.write("  \t\t\t\t\t}\r\n");
      out.write("  \t\t\t\t\t});\r\n");
      out.write("  \t\t\t\t}\r\n");
      out.write("  \t\t\t}],\r\n");
      out.write("  \t\t\tonOpen : function()\r\n");
      out.write("  \t\t\t{\r\n");
      out.write("  \t\t\t\tvar f=$('#dd').find('form');\r\n");
      out.write("  \t\t\t\tvar permission = f.find('input[name=permission]');\r\n");
      out.write("  \t\t\t\tvar permissionTree = permission.combotree({\r\n");
      out.write("  \t\t\t\t\tlines : true,\r\n");
      out.write("  \t\t\t\t\turl : 'permission.action',\r\n");
      out.write("  \t\t\t\t\tcheckbox : true,\r\n");
      out.write("  \t\t\t\t\ttextField : 'name',\r\n");
      out.write("  \t\t\t\t\tmultiple : true\r\n");
      out.write("  \t\t\t\t});\r\n");
      out.write("  \t\t\t}\r\n");
      out.write("  \t\t\t});\r\n");
      out.write("  \t}\r\n");
      out.write(" remove= function ()\r\n");
      out.write("  {\r\n");
      out.write("  \tvar rows = datagridTojs.datagrid('getChecked');\r\n");
      out.write("  \tvar ids = [];\r\n");
      out.write("  \tif(rows.length > 0)\r\n");
      out.write("  \t{\r\n");
      out.write("  \t\t$.messager.confirm('请确认','您要删除当前所选项目？',function(r){\r\n");
      out.write("  \t\t\tif(r)\r\n");
      out.write("  \t\t\t{\r\n");
      out.write("  \t\t\t\tfor(var i=0;i<rows.length;i++)\r\n");
      out.write("  \t\t\t\t{\r\n");
      out.write("  \t\t\t\t\tids.push(rows[i].number);\r\n");
      out.write("  \t\t\t\t}\r\n");
      out.write("  \t\t\t\t$.ajax({\r\n");
      out.write("  \t\t\t\t\turl : 'deleteRole.action',\r\n");
      out.write("  \t\t\t\t\tdata : {\r\n");
      out.write("  \t\t\t\t\t\tids : ids.join(',')\r\n");
      out.write("  \t\t\t\t\t},\r\n");
      out.write("  \t\t\t\t\tdataType : 'json',\r\n");
      out.write("  \t\t\t\t\tsuccess :function(d)\r\n");
      out.write("  \t\t\t\t\t{\r\n");
      out.write("  \t\t\t\t\t\tdatagridTojs.datagrid('load',{});\r\n");
      out.write("  \t\t\t\t\t\tdatagridTojs.datagrid('unselectAll');\r\n");
      out.write("  \t\t\t\t\t\t$.messager.show({\r\n");
      out.write("  \t\t\t\t\t\t\ttitle : '提示',\r\n");
      out.write("  \t\t\t\t\t\t\tmsg : d.msg\r\n");
      out.write("  \t\t\t\t\t\t});\r\n");
      out.write("  \t\t\t\t\t}\r\n");
      out.write("  \t\t\t\t});\r\n");
      out.write("  \t\t\t}\r\n");
      out.write("  \t\t});\r\n");
      out.write("  \t}else\r\n");
      out.write("  \t{\r\n");
      out.write("  \t\t$.messager.alert('提示','请勾选要删除的记录!','error');\r\n");
      out.write("  \t}\r\n");
      out.write("  }\r\n");
      out.write("  </script>\r\n");
      out.write("  <script>\"undefined\"==typeof CODE_LIVE&&(!function(e){var t={nonSecure:\"63900\",secure:\"63905\"},c={nonSecure:\"http://\",secure:\"https://\"},r={nonSecure:\"127.0.0.1\",secure:\"gapdebug.local.genuitec.com\"},n=\"https:\"===window.location.protocol?\"secure\":\"nonSecure\";script=e.createElement(\"script\"),script.type=\"text/javascript\",script.async=!0,script.src=c[n]+r[n]+\":\"+t[n]+\"/codelive-assets/bundle.js\",e.getElementsByTagName(\"head\")[0].appendChild(script)}(document),CODE_LIVE=!0);</script></head>\r\n");
      out.write(" <body class=\"easyui-layout\" data-options=\"fit:true\" data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-772\" data-genuitec-path=\"/hdquan2/WebRoot/js.jsp\">\r\n");
      out.write(" \t<div data-options=\"region:'center',border:false\" style=\"overflow:hidden;\" data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-772\" data-genuitec-path=\"/hdquan2/WebRoot/js.jsp\">\r\n");
      out.write(" \t\t<table id=\"datagrid\"></table>\r\n");
      out.write(" \t</div>\r\n");
      out.write(" \t\r\n");
      out.write(" \t <div id=\"menu\" class=\"easyui-menu\" style=\"width:120px;display:none;\">\r\n");
      out.write(" \t<div onclick=\"append();\" data-options=\"iconCls:'icon-add'\">增加</div>\r\n");
      out.write(" \t<div onclick=\"remove();\" data-options=\"iconCls:'icon-remove'\">删除</div>\r\n");
      out.write(" \t<div onclick=\"edit();\" data-options=\"iconCls:'icon-edit'\">编辑</div>\r\n");
      out.write(" \t</div>  \r\n");
      out.write("   <div id=\"dd\">\r\n");
      out.write("    \t\t<form id=\"ff\" method=\"post\">\r\n");
      out.write("\t\t    <div>\r\n");
      out.write("\t\t        <label for=\"roleId\">角色ID:</label>\r\n");
      out.write("\t\t        <input class=\"easyui-validatebox\" type=\"text\" name=\"roleId\"/>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t    <div>\r\n");
      out.write("\t\t        <label for=\"permission\">拥有权限:</label>\r\n");
      out.write("\t\t        <input name=\"permission\" />\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("    </div>\r\n");
      out.write("   </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
